---
swagger: "2.0"
info:
  description: "An OpenAPI for EVE Online"
  version: "0.8.3"
  title: "EVE Swagger Interface"
host: "esi.evetech.net"
schemes:
- "https"
paths:
  /v1/alliances/:
    get:
      tags:
      - "Alliance"
      summary: "List all alliances"
      description: "List all active player alliances\n\n---\n\nThis route is cached\
        \ for up to 3600 seconds"
      operationId: "get_alliances"
      x-alternate-versions:
      - "dev"
      - "legacy"
      - "v1"
      x-cached-seconds: 3600
  /v1/alliances/{alliance_id}/contacts/labels/:
    get:
      tags:
      - "Contacts"
      summary: "Get alliance contact labels"
      description: "Return custom labels for an alliance's contacts\n\n---\n\nThis\
        \ route is cached for up to 300 seconds"
      operationId: "get_alliances_alliance_id_contacts_labels"
      security:
      - evesso:
        - "esi-alliances.read_contacts.v1"
      x-alternate-versions:
      - "dev"
      - "legacy"
      - "v1"
      x-cached-seconds: 300
  /v1/alliances/{alliance_id}/corporations/:
    get:
      tags:
      - "Alliance"
      summary: "List alliance's corporations"
      description: "List all current member corporations of an alliance\n\n---\n\n\
        This route is cached for up to 3600 seconds"
      operationId: "get_alliances_alliance_id_corporations"
      x-alternate-versions:
      - "dev"
      - "legacy"
      - "v1"
      x-cached-seconds: 3600
  /v1/alliances/{alliance_id}/icons/:
    get:
      tags:
      - "Alliance"
      summary: "Get alliance icon"
      description: "Get the icon urls for a alliance\n\n---\n\nThis route is cached\
        \ for up to 3600 seconds"
      operationId: "get_alliances_alliance_id_icons"
      x-alternate-versions:
      - "dev"
      - "legacy"
      - "v1"
      x-cached-seconds: 3600
  /v1/characters/affiliation/:
    post:
      tags:
      - "Character"
      summary: "Character affiliation"
      description: "Bulk lookup of character IDs to corporation, alliance and faction\n\
        \n---\n\nThis route is cached for up to 3600 seconds"
      operationId: "post_characters_affiliation"
      x-alternate-versions:
      - "dev"
      - "legacy"
      - "v1"
      x-cached-seconds: 3600
  /v1/characters/{character_id}/agents_research/:
    get:
      tags:
      - "Character"
      summary: "Get agents research"
      description: "Return a list of agents research information for a character.\
        \ The formula for finding the current research points with an agent is: currentPoints\
        \ = remainderPoints + pointsPerDay * days(currentTime - researchStartDate)\n\
        \n---\n\nThis route is cached for up to 3600 seconds"
      operationId: "get_characters_character_id_agents_research"
      security:
      - evesso:
        - "esi-characters.read_agents_research.v1"
      x-alternate-versions:
      - "dev"
      - "legacy"
      - "v1"
      x-cached-seconds: 3600
  /v1/characters/{character_id}/assets/names/:
    post:
      tags:
      - "Assets"
      summary: "Get character asset names"
      description: "Return names for a set of item ids, which you can get from character\
        \ assets endpoint. Typically used for items that can customize names, like\
        \ containers or ships.\n\n---\n"
      operationId: "post_characters_character_id_assets_names"
      security:
      - evesso:
        - "esi-assets.read_assets.v1"
      x-alternate-versions:
      - "dev"
      - "legacy"
      - "v1"
  /v1/characters/{character_id}/attributes/:
    get:
      tags:
      - "Skills"
      summary: "Get character attributes"
      description: "Return attributes of a character\n\n---\n\nThis route is cached\
        \ for up to 3600 seconds"
      operationId: "get_characters_character_id_attributes"
      security:
      - evesso:
        - "esi-skills.read_skills.v1"
      x-alternate-versions:
      - "dev"
      - "legacy"
      - "v1"
      x-cached-seconds: 3600
  /v1/characters/{character_id}/calendar/:
    get:
      tags:
      - "Calendar"
      summary: "List calendar event summaries"
      description: "Get 50 event summaries from the calendar. If no from_event ID\
        \ is given, the resource will return the next 50 chronological event summaries\
        \ from now. If a from_event ID is specified, it will return the next 50 chronological\
        \ event summaries from after that event.\n\n---\n\nThis route is cached for\
        \ up to 5 seconds"
      operationId: "get_characters_character_id_calendar"
      security:
      - evesso:
        - "esi-calendar.read_calendar_events.v1"
      x-alternate-versions:
      - "dev"
      - "legacy"
      - "v1"
      x-cached-seconds: 5
  /v1/characters/{character_id}/calendar/{event_id}/attendees/:
    get:
      tags:
      - "Calendar"
      summary: "Get attendees"
      description: "Get all invited attendees for a given event\n\n---\n\nThis route\
        \ is cached for up to 600 seconds"
      operationId: "get_characters_character_id_calendar_event_id_attendees"
      security:
      - evesso:
        - "esi-calendar.read_calendar_events.v1"
      x-alternate-versions:
      - "dev"
      - "legacy"
      - "v1"
      x-cached-seconds: 600
  /v1/characters/{character_id}/contacts/labels/:
    get:
      tags:
      - "Contacts"
      summary: "Get contact labels"
      description: "Return custom labels for a character's contacts\n\n---\n\nThis\
        \ route is cached for up to 300 seconds"
      operationId: "get_characters_character_id_contacts_labels"
      security:
      - evesso:
        - "esi-characters.read_contacts.v1"
      x-alternate-versions:
      - "dev"
      - "legacy"
      - "v1"
      x-cached-seconds: 300
  /v1/characters/{character_id}/contracts/:
    get:
      tags:
      - "Contracts"
      summary: "Get contracts"
      description: "Returns contracts available to a character, only if the character\
        \ is issuer, acceptor or assignee. Only returns contracts no older than 30\
        \ days, or if the status is \"in_progress\".\n\n---\n\nThis route is cached\
        \ for up to 300 seconds"
      operationId: "get_characters_character_id_contracts"
      security:
      - evesso:
        - "esi-contracts.read_character_contracts.v1"
      x-alternate-versions:
      - "dev"
      - "legacy"
      - "v1"
      x-cached-seconds: 300
  /v1/characters/{character_id}/contracts/{contract_id}/bids/:
    get:
      tags:
      - "Contracts"
      summary: "Get contract bids"
      description: "Lists bids on a particular auction contract\n\n---\n\nThis route\
        \ is cached for up to 300 seconds"
      operationId: "get_characters_character_id_contracts_contract_id_bids"
      security:
      - evesso:
        - "esi-contracts.read_character_contracts.v1"
      x-alternate-versions:
      - "dev"
      - "legacy"
      - "v1"
      x-cached-seconds: 300
  /v1/characters/{character_id}/contracts/{contract_id}/items/:
    get:
      tags:
      - "Contracts"
      summary: "Get contract items"
      description: "Lists items of a particular contract\n\n---\n\nThis route is cached\
        \ for up to 3600 seconds"
      operationId: "get_characters_character_id_contracts_contract_id_items"
      security:
      - evesso:
        - "esi-contracts.read_character_contracts.v1"
      x-alternate-versions:
      - "dev"
      - "legacy"
      - "v1"
      x-cached-seconds: 3600
  /v1/characters/{character_id}/corporationhistory/:
    get:
      tags:
      - "Character"
      summary: "Get corporation history"
      description: "Get a list of all the corporations a character has been a member\
        \ of\n\n---\n\nThis route is cached for up to 3600 seconds"
      operationId: "get_characters_character_id_corporationhistory"
      x-alternate-versions:
      - "dev"
      - "legacy"
      - "v1"
      x-cached-seconds: 3600
  /v1/characters/{character_id}/fatigue/:
    get:
      tags:
      - "Character"
      summary: "Get jump fatigue"
      description: "Return a character's jump activation and fatigue information\n\
        \n---\n\nThis route is cached for up to 300 seconds"
      operationId: "get_characters_character_id_fatigue"
      security:
      - evesso:
        - "esi-characters.read_fatigue.v1"
      x-alternate-versions:
      - "dev"
      - "legacy"
      - "v1"
      x-cached-seconds: 300
  /v1/characters/{character_id}/fittings/:
    get:
      tags:
      - "Fittings"
      summary: "Get fittings"
      description: "Return fittings of a character\n\n---\n\nThis route is cached\
        \ for up to 300 seconds"
      operationId: "get_characters_character_id_fittings"
      security:
      - evesso:
        - "esi-fittings.read_fittings.v1"
      x-alternate-versions:
      - "dev"
      - "legacy"
      - "v1"
      x-cached-seconds: 300
    post:
      tags:
      - "Fittings"
      summary: "Create fitting"
      description: "Save a new fitting for a character\n\n---\n"
      operationId: "post_characters_character_id_fittings"
      security:
      - evesso:
        - "esi-fittings.write_fittings.v1"
      x-alternate-versions:
      - "dev"
      - "legacy"
      - "v1"
  /v1/characters/{character_id}/fittings/{fitting_id}/:
    delete:
      tags:
      - "Fittings"
      summary: "Delete fitting"
      description: "Delete a fitting from a character\n\n---\n"
      operationId: "delete_characters_character_id_fittings_fitting_id"
      security:
      - evesso:
        - "esi-fittings.write_fittings.v1"
      x-alternate-versions:
      - "dev"
      - "legacy"
      - "v1"
  /v1/characters/{character_id}/fleet/:
    get:
      tags:
      - "Fleets"
      summary: "Get character fleet info"
      description: "Return the fleet ID the character is in, if any.\n\n---\n\nThis\
        \ route is cached for up to 60 seconds"
      operationId: "get_characters_character_id_fleet"
      security:
      - evesso:
        - "esi-fleets.read_fleet.v1"
      x-alternate-versions:
      - "dev"
      - "legacy"
      - "v1"
      x-cached-seconds: 60
  /v1/characters/{character_id}/fw/stats/:
    get:
      tags:
      - "Faction Warfare"
      summary: "Overview of a character involved in faction warfare"
      description: "Statistical overview of a character involved in faction warfare\n\
        \n---\n\nThis route expires daily at 11:05"
      operationId: "get_characters_character_id_fw_stats"
      security:
      - evesso:
        - "esi-characters.read_fw_stats.v1"
      x-alternate-versions:
      - "dev"
      - "legacy"
      - "v1"
  /v1/characters/{character_id}/implants/:
    get:
      tags:
      - "Clones"
      summary: "Get active implants"
      description: "Return implants on the active clone of a character\n\n---\n\n\
        This route is cached for up to 300 seconds"
      operationId: "get_characters_character_id_implants"
      security:
      - evesso:
        - "esi-clones.read_implants.v1"
      x-alternate-versions:
      - "dev"
      - "legacy"
      - "v1"
      x-cached-seconds: 300
  /v1/characters/{character_id}/industry/jobs/:
    get:
      tags:
      - "Industry"
      summary: "List character industry jobs"
      description: "List industry jobs placed by a character\n\n---\n\nThis route\
        \ is cached for up to 300 seconds"
      operationId: "get_characters_character_id_industry_jobs"
      security:
      - evesso:
        - "esi-industry.read_character_jobs.v1"
      x-alternate-versions:
      - "dev"
      - "legacy"
      - "v1"
      x-cached-seconds: 300
  /v1/characters/{character_id}/killmails/recent/:
    get:
      tags:
      - "Killmails"
      summary: "Get a character's recent kills and losses"
      description: "Return a list of a character's kills and losses going back 90\
        \ days\n\n---\n\nThis route is cached for up to 300 seconds"
      operationId: "get_characters_character_id_killmails_recent"
      security:
      - evesso:
        - "esi-killmails.read_killmails.v1"
      x-alternate-versions:
      - "dev"
      - "legacy"
      - "v1"
      x-cached-seconds: 300
  /v1/characters/{character_id}/location/:
    get:
      tags:
      - "Location"
      summary: "Get character location"
      description: "Information about the characters current location. Returns the\
        \ current solar system id, and also the current station or structure ID if\
        \ applicable.\n\n---\n\nThis route is cached for up to 5 seconds"
      operationId: "get_characters_character_id_location"
      security:
      - evesso:
        - "esi-location.read_location.v1"
      x-alternate-versions:
      - "dev"
      - "legacy"
      - "v1"
      x-cached-seconds: 5
  /v1/characters/{character_id}/loyalty/points/:
    get:
      tags:
      - "Loyalty"
      summary: "Get loyalty points"
      description: "Return a list of loyalty points for all corporations the character\
        \ has worked for\n\n---\n\nThis route is cached for up to 3600 seconds"
      operationId: "get_characters_character_id_loyalty_points"
      security:
      - evesso:
        - "esi-characters.read_loyalty.v1"
      x-alternate-versions:
      - "dev"
      - "legacy"
      - "v1"
      x-cached-seconds: 3600
  /v1/characters/{character_id}/mail/:
    get:
      tags:
      - "Mail"
      summary: "Return mail headers"
      description: "Return the 50 most recent mail headers belonging to the character\
        \ that match the query criteria. Queries can be filtered by label, and last_mail_id\
        \ can be used to paginate backwards.\n\n---\n\nThis route is cached for up\
        \ to 30 seconds"
      operationId: "get_characters_character_id_mail"
      security:
      - evesso:
        - "esi-mail.read_mail.v1"
      x-alternate-versions:
      - "dev"
      - "legacy"
      - "v1"
      x-cached-seconds: 30
    post:
      tags:
      - "Mail"
      summary: "Send a new mail"
      description: "Create and send a new mail\n\n---\n"
      operationId: "post_characters_character_id_mail"
      security:
      - evesso:
        - "esi-mail.send_mail.v1"
      x-alternate-versions:
      - "dev"
      - "legacy"
      - "v1"
  /v1/characters/{character_id}/mail/labels/{label_id}/:
    delete:
      tags:
      - "Mail"
      summary: "Delete a mail label"
      description: "Delete a mail label\n\n---\n"
      operationId: "delete_characters_character_id_mail_labels_label_id"
      security:
      - evesso:
        - "esi-mail.organize_mail.v1"
      x-alternate-versions:
      - "dev"
      - "legacy"
      - "v1"
  /v1/characters/{character_id}/mail/lists/:
    get:
      tags:
      - "Mail"
      summary: "Return mailing list subscriptions"
      description: "Return all mailing lists that the character is subscribed to\n\
        \n---\n\nThis route is cached for up to 120 seconds"
      operationId: "get_characters_character_id_mail_lists"
      security:
      - evesso:
        - "esi-mail.read_mail.v1"
      x-alternate-versions:
      - "dev"
      - "legacy"
      - "v1"
      x-cached-seconds: 120
  /v1/characters/{character_id}/mail/{mail_id}/:
    get:
      tags:
      - "Mail"
      summary: "Return a mail"
      description: "Return the contents of an EVE mail\n\n---\n\nThis route is cached\
        \ for up to 30 seconds"
      operationId: "get_characters_character_id_mail_mail_id"
      security:
      - evesso:
        - "esi-mail.read_mail.v1"
      x-alternate-versions:
      - "dev"
      - "legacy"
      - "v1"
      x-cached-seconds: 30
    put:
      tags:
      - "Mail"
      summary: "Update metadata about a mail"
      description: "Update metadata about a mail\n\n---\n"
      operationId: "put_characters_character_id_mail_mail_id"
      security:
      - evesso:
        - "esi-mail.organize_mail.v1"
      x-alternate-versions:
      - "dev"
      - "legacy"
      - "v1"
    delete:
      tags:
      - "Mail"
      summary: "Delete a mail"
      description: "Delete a mail\n\n---\n"
      operationId: "delete_characters_character_id_mail_mail_id"
      security:
      - evesso:
        - "esi-mail.organize_mail.v1"
      x-alternate-versions:
      - "dev"
      - "legacy"
      - "v1"
  /v1/characters/{character_id}/medals/:
    get:
      tags:
      - "Character"
      summary: "Get medals"
      description: "Return a list of medals the character has\n\n---\n\nThis route\
        \ is cached for up to 3600 seconds"
      operationId: "get_characters_character_id_medals"
      security:
      - evesso:
        - "esi-characters.read_medals.v1"
      x-alternate-versions:
      - "dev"
      - "legacy"
      - "v1"
      x-cached-seconds: 3600
  /v1/characters/{character_id}/mining/:
    get:
      tags:
      - "Industry"
      summary: "Character mining ledger"
      description: "Paginated record of all mining done by a character for the past\
        \ 30 days\n\n---\n\nThis route is cached for up to 600 seconds"
      operationId: "get_characters_character_id_mining"
      security:
      - evesso:
        - "esi-industry.read_character_mining.v1"
      x-alternate-versions:
      - "dev"
      - "legacy"
      - "v1"
      x-cached-seconds: 600
  /v1/characters/{character_id}/notifications/contacts/:
    get:
      tags:
      - "Character"
      summary: "Get new contact notifications"
      description: "Return notifications about having been added to someone's contact\
        \ list\n\n---\n\nThis route is cached for up to 600 seconds"
      operationId: "get_characters_character_id_notifications_contacts"
      security:
      - evesso:
        - "esi-characters.read_notifications.v1"
      x-alternate-versions:
      - "dev"
      - "legacy"
      - "v1"
      x-cached-seconds: 600
  /v1/characters/{character_id}/opportunities/:
    get:
      tags:
      - "Opportunities"
      summary: "Get a character's completed tasks"
      description: "Return a list of tasks finished by a character\n\n---\n\nThis\
        \ route is cached for up to 3600 seconds"
      operationId: "get_characters_character_id_opportunities"
      security:
      - evesso:
        - "esi-characters.read_opportunities.v1"
      x-alternate-versions:
      - "dev"
      - "legacy"
      - "v1"
      x-cached-seconds: 3600
  /v1/characters/{character_id}/orders/history/:
    get:
      tags:
      - "Market"
      summary: "List historical orders by a character"
      description: "List cancelled and expired market orders placed by a character\
        \ up to 90 days in the past.\n\n---\n\nThis route is cached for up to 3600\
        \ seconds"
      operationId: "get_characters_character_id_orders_history"
      security:
      - evesso:
        - "esi-markets.read_character_orders.v1"
      x-alternate-versions:
      - "dev"
      - "legacy"
      - "v1"
      x-cached-seconds: 3600
  /v1/characters/{character_id}/planets/:
    get:
      tags:
      - "Planetary Interaction"
      summary: "Get colonies"
      description: "Returns a list of all planetary colonies owned by a character.\n\
        \n---\n\nThis route is cached for up to 600 seconds"
      operationId: "get_characters_character_id_planets"
      security:
      - evesso:
        - "esi-planets.manage_planets.v1"
      x-alternate-versions:
      - "dev"
      - "legacy"
      - "v1"
      x-cached-seconds: 600
  /v1/characters/{character_id}/ship/:
    get:
      tags:
      - "Location"
      summary: "Get current ship"
      description: "Get the current ship type, name and id\n\n---\n\nThis route is\
        \ cached for up to 5 seconds"
      operationId: "get_characters_character_id_ship"
      security:
      - evesso:
        - "esi-location.read_ship_type.v1"
      x-alternate-versions:
      - "dev"
      - "legacy"
      - "v1"
      x-cached-seconds: 5
  /v1/characters/{character_id}/standings/:
    get:
      tags:
      - "Character"
      summary: "Get standings"
      description: "Return character standings from agents, NPC corporations, and\
        \ factions\n\n---\n\nThis route is cached for up to 3600 seconds"
      operationId: "get_characters_character_id_standings"
      security:
      - evesso:
        - "esi-characters.read_standings.v1"
      x-alternate-versions:
      - "dev"
      - "legacy"
      - "v1"
      x-cached-seconds: 3600
  /v1/characters/{character_id}/titles/:
    get:
      tags:
      - "Character"
      summary: "Get character corporation titles"
      description: "Returns a character's titles\n\n---\n\nThis route is cached for\
        \ up to 3600 seconds"
      operationId: "get_characters_character_id_titles"
      security:
      - evesso:
        - "esi-characters.read_titles.v1"
      x-alternate-versions:
      - "dev"
      - "legacy"
      - "v1"
      x-cached-seconds: 3600
  /v1/characters/{character_id}/wallet/:
    get:
      tags:
      - "Wallet"
      summary: "Get a character's wallet balance"
      description: "Returns a character's wallet balance\n\n---\n\nThis route is cached\
        \ for up to 120 seconds"
      operationId: "get_characters_character_id_wallet"
      security:
      - evesso:
        - "esi-wallet.read_character_wallet.v1"
      x-alternate-versions:
      - "dev"
      - "legacy"
      - "v1"
      x-cached-seconds: 120
  /v1/characters/{character_id}/wallet/transactions/:
    get:
      tags:
      - "Wallet"
      summary: "Get wallet transactions"
      description: "Get wallet transactions of a character\n\n---\n\nThis route is\
        \ cached for up to 3600 seconds"
      operationId: "get_characters_character_id_wallet_transactions"
      security:
      - evesso:
        - "esi-wallet.read_character_wallet.v1"
      x-alternate-versions:
      - "dev"
      - "legacy"
      - "v1"
      x-cached-seconds: 3600
  /v1/corporation/{corporation_id}/mining/extractions/:
    get:
      tags:
      - "Industry"
      summary: "Moon extraction timers"
      description: "Extraction timers for all moon chunks being extracted by refineries\
        \ belonging to a corporation.\n\n---\n\nThis route is cached for up to 1800\
        \ seconds\n\n---\nRequires one of the following EVE corporation role(s): Structure_manager"
      operationId: "get_corporation_corporation_id_mining_extractions"
      security:
      - evesso:
        - "esi-industry.read_corporation_mining.v1"
      x-alternate-versions:
      - "dev"
      - "legacy"
      - "v1"
      x-cached-seconds: 1800
      x-required-roles:
      - "Structure_manager"
  /v1/corporation/{corporation_id}/mining/observers/:
    get:
      tags:
      - "Industry"
      summary: "Corporation mining observers"
      description: "Paginated list of all entities capable of observing and recording\
        \ mining for a corporation\n\n---\n\nThis route is cached for up to 3600 seconds\n\
        \n---\nRequires one of the following EVE corporation role(s): Accountant"
      operationId: "get_corporation_corporation_id_mining_observers"
      security:
      - evesso:
        - "esi-industry.read_corporation_mining.v1"
      x-alternate-versions:
      - "dev"
      - "legacy"
      - "v1"
      x-cached-seconds: 3600
      x-required-roles:
      - "Accountant"
  /v1/corporation/{corporation_id}/mining/observers/{observer_id}/:
    get:
      tags:
      - "Industry"
      summary: "Observed corporation mining"
      description: "Paginated record of all mining seen by an observer\n\n---\n\n\
        This route is cached for up to 3600 seconds\n\n---\nRequires one of the following\
        \ EVE corporation role(s): Accountant"
      operationId: "get_corporation_corporation_id_mining_observers_observer_id"
      security:
      - evesso:
        - "esi-industry.read_corporation_mining.v1"
      x-alternate-versions:
      - "dev"
      - "legacy"
      - "v1"
      x-cached-seconds: 3600
      x-required-roles:
      - "Accountant"
  /v1/corporations/npccorps/:
    get:
      tags:
      - "Corporation"
      summary: "Get npc corporations"
      description: "Get a list of npc corporations\n\n---\n\nThis route expires daily\
        \ at 11:05"
      operationId: "get_corporations_npccorps"
      x-alternate-versions:
      - "dev"
      - "legacy"
      - "v1"
  /v1/corporations/{corporation_id}/assets/names/:
    post:
      tags:
      - "Assets"
      summary: "Get coporation asset names"
      description: "Return names for a set of item ids, which you can get from corporation\
        \ assets endpoint. Only valid for items that can customize names, like containers\
        \ or ships.\n\n---\n\nRequires one of the following EVE corporation role(s):\
        \ Director"
      operationId: "post_corporations_corporation_id_assets_names"
      security:
      - evesso:
        - "esi-assets.read_corporation_assets.v1"
      x-alternate-versions:
      - "dev"
      - "legacy"
      - "v1"
      x-required-roles:
      - "Director"
  /v1/corporations/{corporation_id}/bookmarks/:
    get:
      tags:
      - "Bookmarks"
      summary: "List corporation bookmarks"
      description: "A list of your corporation's bookmarks\n\n---\n\nThis route is\
        \ cached for up to 3600 seconds"
      operationId: "get_corporations_corporation_id_bookmarks"
      security:
      - evesso:
        - "esi-bookmarks.read_corporation_bookmarks.v1"
      x-alternate-versions:
      - "dev"
      - "legacy"
      - "v1"
      x-cached-seconds: 3600
  /v1/corporations/{corporation_id}/bookmarks/folders/:
    get:
      tags:
      - "Bookmarks"
      summary: "List corporation bookmark folders"
      description: "A list of your corporation's bookmark folders\n\n---\n\nThis route\
        \ is cached for up to 3600 seconds"
      operationId: "get_corporations_corporation_id_bookmarks_folders"
      security:
      - evesso:
        - "esi-bookmarks.read_corporation_bookmarks.v1"
      x-alternate-versions:
      - "dev"
      - "legacy"
      - "v1"
      x-cached-seconds: 3600
  /v1/corporations/{corporation_id}/contacts/labels/:
    get:
      tags:
      - "Contacts"
      summary: "Get corporation contact labels"
      description: "Return custom labels for a corporation's contacts\n\n---\n\nThis\
        \ route is cached for up to 300 seconds"
      operationId: "get_corporations_corporation_id_contacts_labels"
      security:
      - evesso:
        - "esi-corporations.read_contacts.v1"
      x-alternate-versions:
      - "dev"
      - "legacy"
      - "v1"
      x-cached-seconds: 300
      x-required-roles: []
  /v1/corporations/{corporation_id}/contracts/:
    get:
      tags:
      - "Contracts"
      summary: "Get corporation contracts"
      description: "Returns contracts available to a corporation, only if the corporation\
        \ is issuer, acceptor or assignee. Only returns contracts no older than 30\
        \ days, or if the status is \"in_progress\".\n\n---\n\nThis route is cached\
        \ for up to 300 seconds"
      operationId: "get_corporations_corporation_id_contracts"
      security:
      - evesso:
        - "esi-contracts.read_corporation_contracts.v1"
      x-alternate-versions:
      - "dev"
      - "legacy"
      - "v1"
      x-cached-seconds: 300
      x-required-roles: []
  /v1/corporations/{corporation_id}/contracts/{contract_id}/bids/:
    get:
      tags:
      - "Contracts"
      summary: "Get corporation contract bids"
      description: "Lists bids on a particular auction contract\n\n---\n\nThis route\
        \ is cached for up to 3600 seconds"
      operationId: "get_corporations_corporation_id_contracts_contract_id_bids"
      security:
      - evesso:
        - "esi-contracts.read_corporation_contracts.v1"
      x-alternate-versions:
      - "dev"
      - "legacy"
      - "v1"
      x-cached-seconds: 3600
      x-required-roles: []
  /v1/corporations/{corporation_id}/contracts/{contract_id}/items/:
    get:
      tags:
      - "Contracts"
      summary: "Get corporation contract items"
      description: "Lists items of a particular contract\n\n---\n\nThis route is cached\
        \ for up to 3600 seconds"
      operationId: "get_corporations_corporation_id_contracts_contract_id_items"
      security:
      - evesso:
        - "esi-contracts.read_corporation_contracts.v1"
      x-alternate-versions:
      - "dev"
      - "legacy"
      - "v1"
      x-cached-seconds: 3600
      x-required-roles: []
  /v1/corporations/{corporation_id}/customs_offices/:
    get:
      tags:
      - "Planetary Interaction"
      summary: "List corporation customs offices"
      description: "List customs offices owned by a corporation\n\n---\n\nThis route\
        \ is cached for up to 3600 seconds\n\n---\nRequires one of the following EVE\
        \ corporation role(s): Director"
      operationId: "get_corporations_corporation_id_customs_offices"
      security:
      - evesso:
        - "esi-planets.read_customs_offices.v1"
      x-alternate-versions:
      - "dev"
      - "legacy"
      - "v1"
      x-cached-seconds: 3600
      x-required-roles:
      - "Director"
  /v1/corporations/{corporation_id}/divisions/:
    get:
      tags:
      - "Corporation"
      summary: "Get corporation divisions"
      description: "Return corporation hangar and wallet division names, only show\
        \ if a division is not using the default name\n\n---\n\nThis route is cached\
        \ for up to 3600 seconds\n\n---\nRequires one of the following EVE corporation\
        \ role(s): Director"
      operationId: "get_corporations_corporation_id_divisions"
      security:
      - evesso:
        - "esi-corporations.read_divisions.v1"
      x-alternate-versions:
      - "dev"
      - "legacy"
      - "v1"
      x-cached-seconds: 3600
      x-required-roles:
      - "Director"
  /v1/corporations/{corporation_id}/facilities/:
    get:
      tags:
      - "Corporation"
      summary: "Get corporation facilities"
      description: "Return a corporation's facilities\n\n---\n\nThis route is cached\
        \ for up to 3600 seconds\n\n---\nRequires one of the following EVE corporation\
        \ role(s): Factory_Manager"
      operationId: "get_corporations_corporation_id_facilities"
      security:
      - evesso:
        - "esi-corporations.read_facilities.v1"
      x-alternate-versions:
      - "dev"
      - "legacy"
      - "v1"
      x-cached-seconds: 3600
      x-required-roles:
      - "Factory_Manager"
  /v1/corporations/{corporation_id}/fw/stats/:
    get:
      tags:
      - "Faction Warfare"
      summary: "Overview of a corporation involved in faction warfare"
      description: "Statistics about a corporation involved in faction warfare\n\n\
        ---\n\nThis route expires daily at 11:05"
      operationId: "get_corporations_corporation_id_fw_stats"
      security:
      - evesso:
        - "esi-corporations.read_fw_stats.v1"
      x-alternate-versions:
      - "dev"
      - "legacy"
      - "v1"
      x-required-roles: []
  /v1/corporations/{corporation_id}/icons/:
    get:
      tags:
      - "Corporation"
      summary: "Get corporation icon"
      description: "Get the icon urls for a corporation\n\n---\n\nThis route is cached\
        \ for up to 3600 seconds"
      operationId: "get_corporations_corporation_id_icons"
      x-alternate-versions:
      - "dev"
      - "legacy"
      - "v1"
      x-cached-seconds: 3600
  /v1/corporations/{corporation_id}/industry/jobs/:
    get:
      tags:
      - "Industry"
      summary: "List corporation industry jobs"
      description: "List industry jobs run by a corporation\n\n---\n\nThis route is\
        \ cached for up to 300 seconds\n\n---\nRequires one of the following EVE corporation\
        \ role(s): FactoryManager"
      operationId: "get_corporations_corporation_id_industry_jobs"
      security:
      - evesso:
        - "esi-industry.read_corporation_jobs.v1"
      x-alternate-versions:
      - "dev"
      - "legacy"
      - "v1"
      x-cached-seconds: 300
      x-required-roles:
      - "FactoryManager"
  /v1/corporations/{corporation_id}/killmails/recent/:
    get:
      tags:
      - "Killmails"
      summary: "Get a corporation's recent kills and losses"
      description: "Get a list of a corporation's kills and losses going back 90 days\n\
        \n---\n\nThis route is cached for up to 300 seconds\n\n---\nRequires one of\
        \ the following EVE corporation role(s): Director"
      operationId: "get_corporations_corporation_id_killmails_recent"
      security:
      - evesso:
        - "esi-killmails.read_corporation_killmails.v1"
      x-alternate-versions:
      - "dev"
      - "legacy"
      - "v1"
      x-cached-seconds: 300
      x-required-roles:
      - "Director"
  /v1/corporations/{corporation_id}/medals/:
    get:
      tags:
      - "Corporation"
      summary: "Get corporation medals"
      description: "Returns a corporation's medals\n\n---\n\nThis route is cached\
        \ for up to 3600 seconds"
      operationId: "get_corporations_corporation_id_medals"
      security:
      - evesso:
        - "esi-corporations.read_medals.v1"
      x-alternate-versions:
      - "dev"
      - "legacy"
      - "v1"
      x-cached-seconds: 3600
      x-required-roles: []
  /v1/corporations/{corporation_id}/medals/issued/:
    get:
      tags:
      - "Corporation"
      summary: "Get corporation issued medals"
      description: "Returns medals issued by a corporation\n\n---\n\nThis route is\
        \ cached for up to 3600 seconds\n\n---\nRequires one of the following EVE\
        \ corporation role(s): Director"
      operationId: "get_corporations_corporation_id_medals_issued"
      security:
      - evesso:
        - "esi-corporations.read_medals.v1"
      x-alternate-versions:
      - "dev"
      - "legacy"
      - "v1"
      x-cached-seconds: 3600
      x-required-roles:
      - "Director"
  /v1/corporations/{corporation_id}/members/limit/:
    get:
      tags:
      - "Corporation"
      summary: "Get corporation member limit"
      description: "Return a corporation's member limit, not including CEO himself\n\
        \n---\n\nThis route is cached for up to 3600 seconds\n\n---\nRequires one\
        \ of the following EVE corporation role(s): Director"
      operationId: "get_corporations_corporation_id_members_limit"
      security:
      - evesso:
        - "esi-corporations.track_members.v1"
      x-alternate-versions:
      - "dev"
      - "legacy"
      - "v1"
      x-cached-seconds: 3600
      x-required-roles:
      - "Director"
  /v1/corporations/{corporation_id}/members/titles/:
    get:
      tags:
      - "Corporation"
      summary: "Get corporation's members' titles"
      description: "Returns a corporation's members' titles\n\n---\n\nThis route is\
        \ cached for up to 3600 seconds\n\n---\nRequires one of the following EVE\
        \ corporation role(s): Director"
      operationId: "get_corporations_corporation_id_members_titles"
      security:
      - evesso:
        - "esi-corporations.read_titles.v1"
      x-alternate-versions:
      - "dev"
      - "legacy"
      - "v1"
      x-cached-seconds: 3600
      x-required-roles:
      - "Director"
  /v1/corporations/{corporation_id}/membertracking/:
    get:
      tags:
      - "Corporation"
      summary: "Track corporation members"
      description: "Returns additional information about a corporation's members which\
        \ helps tracking their activities\n\n---\n\nThis route is cached for up to\
        \ 3600 seconds\n\n---\nRequires one of the following EVE corporation role(s):\
        \ Director"
      operationId: "get_corporations_corporation_id_membertracking"
      security:
      - evesso:
        - "esi-corporations.track_members.v1"
      x-alternate-versions:
      - "dev"
      - "legacy"
      - "v1"
      x-cached-seconds: 3600
      x-required-roles:
      - "Director"
  /v1/corporations/{corporation_id}/orders/history/:
    get:
      tags:
      - "Market"
      summary: "List historical orders from a corporation"
      description: "List cancelled and expired market orders placed on behalf of a\
        \ corporation up to 90 days in the past.\n\n---\n\nThis route is cached for\
        \ up to 3600 seconds\n\n---\nRequires one of the following EVE corporation\
        \ role(s): Accountant, Trader\n\n---\nWarning: This route has an upgrade available.\n\
        \n---\n[Diff of the upcoming changes](https://esi.evetech.net/diff/latest/dev/#GET-/corporations/{corporation_id}/orders/history/)"
      operationId: "get_corporations_corporation_id_orders_history"
      security:
      - evesso:
        - "esi-markets.read_corporation_orders.v1"
      x-alternate-versions:
      - "legacy"
      - "v1"
      x-cached-seconds: 3600
      x-required-roles:
      - "Accountant"
      - "Trader"
  /v1/corporations/{corporation_id}/outposts/:
    get:
      tags:
      - "Corporation"
      summary: "Get corporation outposts"
      description: "Get a list of corporation outpost IDs Note: This endpoint will\
        \ be removed once outposts are migrated to Citadels as talked about in this\
        \ blog: https://community.eveonline.com/news/dev-blogs/the-next-steps-in-structure-transition/\n\
        \n---\n\nThis route is cached for up to 3600 seconds\n\n---\nRequires one\
        \ of the following EVE corporation role(s): Director"
      operationId: "get_corporations_corporation_id_outposts"
      security:
      - evesso:
        - "esi-corporations.read_outposts.v1"
      x-alternate-versions:
      - "dev"
      - "legacy"
      - "v1"
      x-cached-seconds: 3600
      x-required-roles:
      - "Director"
  /v1/corporations/{corporation_id}/outposts/{outpost_id}/:
    get:
      tags:
      - "Corporation"
      summary: "Get corporation outpost details"
      description: "Get details about a given outpost. Note: This endpoint will be\
        \ removed once outposts are migrated to Citadels as talked about in this blog:\
        \ https://community.eveonline.com/news/dev-blogs/the-next-steps-in-structure-transition/\n\
        \n---\n\nThis route is cached for up to 3600 seconds\n\n---\nRequires one\
        \ of the following EVE corporation role(s): Director"
      operationId: "get_corporations_corporation_id_outposts_outpost_id"
      security:
      - evesso:
        - "esi-corporations.read_outposts.v1"
      x-alternate-versions:
      - "dev"
      - "legacy"
      - "v1"
      x-cached-seconds: 3600
      x-required-roles:
      - "Director"
  /v1/corporations/{corporation_id}/roles/:
    get:
      tags:
      - "Corporation"
      summary: "Get corporation member roles"
      description: "Return the roles of all members if the character has the personnel\
        \ manager role or any grantable role.\n\n---\n\nThis route is cached for up\
        \ to 3600 seconds"
      operationId: "get_corporations_corporation_id_roles"
      security:
      - evesso:
        - "esi-corporations.read_corporation_membership.v1"
      x-alternate-versions:
      - "dev"
      - "legacy"
      - "v1"
      x-cached-seconds: 3600
  /v1/corporations/{corporation_id}/roles/history/:
    get:
      tags:
      - "Corporation"
      summary: "Get corporation member roles history"
      description: "Return how roles have changed for a coporation's members, up to\
        \ a month\n\n---\n\nThis route is cached for up to 3600 seconds\n\n---\nRequires\
        \ one of the following EVE corporation role(s): Director"
      operationId: "get_corporations_corporation_id_roles_history"
      security:
      - evesso:
        - "esi-corporations.read_corporation_membership.v1"
      x-alternate-versions:
      - "dev"
      - "legacy"
      - "v1"
      x-cached-seconds: 3600
      x-required-roles:
      - "Director"
  /v1/corporations/{corporation_id}/shareholders/:
    get:
      tags:
      - "Corporation"
      summary: "Get corporation shareholders"
      description: "Return the current shareholders of a corporation.\n\n---\n\nThis\
        \ route is cached for up to 3600 seconds\n\n---\nRequires one of the following\
        \ EVE corporation role(s): Director"
      operationId: "get_corporations_corporation_id_shareholders"
      security:
      - evesso:
        - "esi-wallet.read_corporation_wallets.v1"
      x-alternate-versions:
      - "dev"
      - "legacy"
      - "v1"
      x-cached-seconds: 3600
      x-required-roles:
      - "Director"
  /v1/corporations/{corporation_id}/standings/:
    get:
      tags:
      - "Corporation"
      summary: "Get corporation standings"
      description: "Return corporation standings from agents, NPC corporations, and\
        \ factions\n\n---\n\nThis route is cached for up to 3600 seconds"
      operationId: "get_corporations_corporation_id_standings"
      security:
      - evesso:
        - "esi-corporations.read_standings.v1"
      x-alternate-versions:
      - "dev"
      - "legacy"
      - "v1"
      x-cached-seconds: 3600
      x-required-roles: []
  /v1/corporations/{corporation_id}/starbases/:
    get:
      tags:
      - "Corporation"
      summary: "Get corporation starbases (POSes)"
      description: "Returns list of corporation starbases (POSes)\n\n---\n\nThis route\
        \ is cached for up to 3600 seconds\n\n---\nRequires one of the following EVE\
        \ corporation role(s): Director"
      operationId: "get_corporations_corporation_id_starbases"
      security:
      - evesso:
        - "esi-corporations.read_starbases.v1"
      x-alternate-versions:
      - "dev"
      - "legacy"
      - "v1"
      x-cached-seconds: 3600
      x-required-roles:
      - "Director"
  /v1/corporations/{corporation_id}/starbases/{starbase_id}/:
    get:
      tags:
      - "Corporation"
      summary: "Get starbase (POS) detail"
      description: "Returns various settings and fuels of a starbase (POS)\n\n---\n\
        \nThis route is cached for up to 3600 seconds\n\n---\nRequires one of the\
        \ following EVE corporation role(s): Director"
      operationId: "get_corporations_corporation_id_starbases_starbase_id"
      security:
      - evesso:
        - "esi-corporations.read_starbases.v1"
      x-alternate-versions:
      - "dev"
      - "legacy"
      - "v1"
      x-cached-seconds: 3600
      x-required-roles:
      - "Director"
  /v1/corporations/{corporation_id}/titles/:
    get:
      tags:
      - "Corporation"
      summary: "Get corporation titles"
      description: "Returns a corporation's titles\n\n---\n\nThis route is cached\
        \ for up to 3600 seconds\n\n---\nRequires one of the following EVE corporation\
        \ role(s): Director"
      operationId: "get_corporations_corporation_id_titles"
      security:
      - evesso:
        - "esi-corporations.read_titles.v1"
      x-alternate-versions:
      - "dev"
      - "legacy"
      - "v1"
      x-cached-seconds: 3600
      x-required-roles:
      - "Director"
  /v1/corporations/{corporation_id}/wallets/:
    get:
      tags:
      - "Wallet"
      summary: "Returns a corporation's wallet balance"
      description: "Get a corporation's wallets\n\n---\n\nThis route is cached for\
        \ up to 300 seconds\n\n---\nRequires one of the following EVE corporation\
        \ role(s): Accountant, Junior_Accountant"
      operationId: "get_corporations_corporation_id_wallets"
      security:
      - evesso:
        - "esi-wallet.read_corporation_wallets.v1"
      x-alternate-versions:
      - "dev"
      - "legacy"
      - "v1"
      x-cached-seconds: 300
      x-required-roles:
      - "Accountant"
      - "Junior_Accountant"
  /v1/corporations/{corporation_id}/wallets/{division}/transactions/:
    get:
      tags:
      - "Wallet"
      summary: "Get corporation wallet transactions"
      description: "Get wallet transactions of a corporation\n\n---\n\nThis route\
        \ is cached for up to 3600 seconds\n\n---\nRequires one of the following EVE\
        \ corporation role(s): Accountant, Junior_Accountant"
      operationId: "get_corporations_corporation_id_wallets_division_transactions"
      security:
      - evesso:
        - "esi-wallet.read_corporation_wallets.v1"
      x-alternate-versions:
      - "dev"
      - "legacy"
      - "v1"
      x-cached-seconds: 3600
      x-required-roles:
      - "Accountant"
      - "Junior_Accountant"
  /v1/dogma/attributes/:
    get:
      tags:
      - "Dogma"
      summary: "Get attributes"
      description: "Get a list of dogma attribute ids\n\n---\n\nThis route expires\
        \ daily at 11:05"
      operationId: "get_dogma_attributes"
      x-alternate-versions:
      - "dev"
      - "legacy"
      - "v1"
  /v1/dogma/attributes/{attribute_id}/:
    get:
      tags:
      - "Dogma"
      summary: "Get attribute information"
      description: "Get information on a dogma attribute\n\n---\n\nThis route expires\
        \ daily at 11:05"
      operationId: "get_dogma_attributes_attribute_id"
      x-alternate-versions:
      - "dev"
      - "legacy"
      - "v1"
  /v1/dogma/dynamic/items/{type_id}/{item_id}/:
    get:
      tags:
      - "Dogma"
      summary: "Get dynamic item information"
      description: "Returns info about a dynamic item resulting from mutation with\
        \ a mutaplasmid.\n\n---\n\nThis route expires daily at 11:05"
      operationId: "get_dogma_dynamic_items_type_id_item_id"
      x-alternate-versions:
      - "dev"
      - "legacy"
      - "v1"
  /v1/dogma/effects/:
    get:
      tags:
      - "Dogma"
      summary: "Get effects"
      description: "Get a list of dogma effect ids\n\n---\n\nThis route expires daily\
        \ at 11:05"
      operationId: "get_dogma_effects"
      x-alternate-versions:
      - "dev"
      - "legacy"
      - "v1"
  /v1/fleets/{fleet_id}/:
    get:
      tags:
      - "Fleets"
      summary: "Get fleet information"
      description: "Return details about a fleet\n\n---\n\nThis route is cached for\
        \ up to 5 seconds"
      operationId: "get_fleets_fleet_id"
      security:
      - evesso:
        - "esi-fleets.read_fleet.v1"
      x-alternate-versions:
      - "dev"
      - "legacy"
      - "v1"
      x-cached-seconds: 5
    put:
      tags:
      - "Fleets"
      summary: "Update fleet"
      description: "Update settings about a fleet\n\n---\n"
      operationId: "put_fleets_fleet_id"
      security:
      - evesso:
        - "esi-fleets.write_fleet.v1"
      x-alternate-versions:
      - "dev"
      - "legacy"
      - "v1"
  /v1/fleets/{fleet_id}/members/:
    get:
      tags:
      - "Fleets"
      summary: "Get fleet members"
      description: "Return information about fleet members\n\n---\n\nThis route is\
        \ cached for up to 5 seconds"
      operationId: "get_fleets_fleet_id_members"
      security:
      - evesso:
        - "esi-fleets.read_fleet.v1"
      x-alternate-versions:
      - "dev"
      - "legacy"
      - "v1"
      x-cached-seconds: 5
    post:
      tags:
      - "Fleets"
      summary: "Create fleet invitation"
      description: "Invite a character into the fleet. If a character has a CSPA charge\
        \ set it is not possible to invite them to the fleet using ESI\n\n---\n"
      operationId: "post_fleets_fleet_id_members"
      security:
      - evesso:
        - "esi-fleets.write_fleet.v1"
      x-alternate-versions:
      - "dev"
      - "legacy"
      - "v1"
  /v1/fleets/{fleet_id}/members/{member_id}/:
    put:
      tags:
      - "Fleets"
      summary: "Move fleet member"
      description: "Move a fleet member around\n\n---\n"
      operationId: "put_fleets_fleet_id_members_member_id"
      security:
      - evesso:
        - "esi-fleets.write_fleet.v1"
      x-alternate-versions:
      - "dev"
      - "legacy"
      - "v1"
    delete:
      tags:
      - "Fleets"
      summary: "Kick fleet member"
      description: "Kick a fleet member\n\n---\n"
      operationId: "delete_fleets_fleet_id_members_member_id"
      security:
      - evesso:
        - "esi-fleets.write_fleet.v1"
      x-alternate-versions:
      - "dev"
      - "legacy"
      - "v1"
  /v1/fleets/{fleet_id}/squads/{squad_id}/:
    put:
      tags:
      - "Fleets"
      summary: "Rename fleet squad"
      description: "Rename a fleet squad\n\n---\n"
      operationId: "put_fleets_fleet_id_squads_squad_id"
      security:
      - evesso:
        - "esi-fleets.write_fleet.v1"
      x-alternate-versions:
      - "dev"
      - "legacy"
      - "v1"
    delete:
      tags:
      - "Fleets"
      summary: "Delete fleet squad"
      description: "Delete a fleet squad, only empty squads can be deleted\n\n---\n"
      operationId: "delete_fleets_fleet_id_squads_squad_id"
      security:
      - evesso:
        - "esi-fleets.write_fleet.v1"
      x-alternate-versions:
      - "dev"
      - "legacy"
      - "v1"
  /v1/fleets/{fleet_id}/wings/:
    get:
      tags:
      - "Fleets"
      summary: "Get fleet wings"
      description: "Return information about wings in a fleet\n\n---\n\nThis route\
        \ is cached for up to 5 seconds"
      operationId: "get_fleets_fleet_id_wings"
      security:
      - evesso:
        - "esi-fleets.read_fleet.v1"
      x-alternate-versions:
      - "dev"
      - "legacy"
      - "v1"
      x-cached-seconds: 5
    post:
      tags:
      - "Fleets"
      summary: "Create fleet wing"
      description: "Create a new wing in a fleet\n\n---\n"
      operationId: "post_fleets_fleet_id_wings"
      security:
      - evesso:
        - "esi-fleets.write_fleet.v1"
      x-alternate-versions:
      - "dev"
      - "legacy"
      - "v1"
  /v1/fleets/{fleet_id}/wings/{wing_id}/:
    put:
      tags:
      - "Fleets"
      summary: "Rename fleet wing"
      description: "Rename a fleet wing\n\n---\n"
      operationId: "put_fleets_fleet_id_wings_wing_id"
      security:
      - evesso:
        - "esi-fleets.write_fleet.v1"
      x-alternate-versions:
      - "dev"
      - "legacy"
      - "v1"
    delete:
      tags:
      - "Fleets"
      summary: "Delete fleet wing"
      description: "Delete a fleet wing, only empty wings can be deleted. The wing\
        \ may contain squads, but the squads must be empty\n\n---\n"
      operationId: "delete_fleets_fleet_id_wings_wing_id"
      security:
      - evesso:
        - "esi-fleets.write_fleet.v1"
      x-alternate-versions:
      - "dev"
      - "legacy"
      - "v1"
  /v1/fleets/{fleet_id}/wings/{wing_id}/squads/:
    post:
      tags:
      - "Fleets"
      summary: "Create fleet squad"
      description: "Create a new squad in a fleet\n\n---\n"
      operationId: "post_fleets_fleet_id_wings_wing_id_squads"
      security:
      - evesso:
        - "esi-fleets.write_fleet.v1"
      x-alternate-versions:
      - "dev"
      - "legacy"
      - "v1"
  /v1/fw/leaderboards/:
    get:
      tags:
      - "Faction Warfare"
      summary: "List of the top factions in faction warfare"
      description: "Top 4 leaderboard of factions for kills and victory points separated\
        \ by total, last week and yesterday.\n\n---\n\nThis route expires daily at\
        \ 11:05"
      operationId: "get_fw_leaderboards"
      x-alternate-versions:
      - "dev"
      - "legacy"
      - "v1"
  /v1/fw/leaderboards/characters/:
    get:
      tags:
      - "Faction Warfare"
      summary: "List of the top pilots in faction warfare"
      description: "Top 100 leaderboard of pilots for kills and victory points separated\
        \ by total, last week and yesterday.\n\n---\n\nThis route expires daily at\
        \ 11:05"
      operationId: "get_fw_leaderboards_characters"
      x-alternate-versions:
      - "dev"
      - "legacy"
      - "v1"
  /v1/fw/leaderboards/corporations/:
    get:
      tags:
      - "Faction Warfare"
      summary: "List of the top corporations in faction warfare"
      description: "Top 10 leaderboard of corporations for kills and victory points\
        \ separated by total, last week and yesterday.\n\n---\n\nThis route expires\
        \ daily at 11:05"
      operationId: "get_fw_leaderboards_corporations"
      x-alternate-versions:
      - "dev"
      - "legacy"
      - "v1"
  /v1/fw/stats/:
    get:
      tags:
      - "Faction Warfare"
      summary: "An overview of statistics about factions involved in faction warfare"
      description: "Statistical overviews of factions involved in faction warfare\n\
        \n---\n\nThis route expires daily at 11:05"
      operationId: "get_fw_stats"
      x-alternate-versions:
      - "dev"
      - "legacy"
      - "v1"
  /v1/fw/systems/:
    get:
      tags:
      - "Faction Warfare"
      summary: "Ownership of faction warfare systems"
      description: "An overview of the current ownership of faction warfare solar\
        \ systems\n\n---\n\nThis route is cached for up to 1800 seconds\n\n---\nWarning:\
        \ This route has an upgrade available.\n\n---\n[Diff of the upcoming changes](https://esi.evetech.net/diff/latest/dev/#GET-/fw/systems/)"
      operationId: "get_fw_systems"
      x-alternate-versions:
      - "legacy"
      - "v1"
      x-cached-seconds: 1800
  /v1/fw/wars/:
    get:
      tags:
      - "Faction Warfare"
      summary: "Data about which NPC factions are at war"
      description: "Data about which NPC factions are at war\n\n---\n\nThis route\
        \ expires daily at 11:05"
      operationId: "get_fw_wars"
      x-alternate-versions:
      - "dev"
      - "legacy"
      - "v1"
  /v1/incursions/:
    get:
      tags:
      - "Incursions"
      summary: "List incursions"
      description: "Return a list of current incursions\n\n---\n\nThis route is cached\
        \ for up to 300 seconds"
      operationId: "get_incursions"
      x-alternate-versions:
      - "dev"
      - "legacy"
      - "v1"
      x-cached-seconds: 300
  /v1/industry/facilities/:
    get:
      tags:
      - "Industry"
      summary: "List industry facilities"
      description: "Return a list of industry facilities\n\n---\n\nThis route is cached\
        \ for up to 3600 seconds"
      operationId: "get_industry_facilities"
      x-alternate-versions:
      - "dev"
      - "legacy"
      - "v1"
      x-cached-seconds: 3600
  /v1/industry/systems/:
    get:
      tags:
      - "Industry"
      summary: "List solar system cost indices"
      description: "Return cost indices for solar systems\n\n---\n\nThis route is\
        \ cached for up to 3600 seconds"
      operationId: "get_industry_systems"
      x-alternate-versions:
      - "dev"
      - "legacy"
      - "v1"
      x-cached-seconds: 3600
  /v1/insurance/prices/:
    get:
      tags:
      - "Insurance"
      summary: "List insurance levels"
      description: "Return available insurance levels for all ship types\n\n---\n\n\
        This route is cached for up to 3600 seconds"
      operationId: "get_insurance_prices"
      x-alternate-versions:
      - "dev"
      - "legacy"
      - "v1"
      x-cached-seconds: 3600
  /v1/killmails/{killmail_id}/{killmail_hash}/:
    get:
      tags:
      - "Killmails"
      summary: "Get a single killmail"
      description: "Return a single killmail from its ID and hash\n\n---\n\nThis route\
        \ is cached for up to 1209600 seconds"
      operationId: "get_killmails_killmail_id_killmail_hash"
      x-alternate-versions:
      - "dev"
      - "legacy"
      - "v1"
      x-cached-seconds: 1209600
  /v1/loyalty/stores/{corporation_id}/offers/:
    get:
      tags:
      - "Loyalty"
      summary: "List loyalty store offers"
      description: "Return a list of offers from a specific corporation's loyalty\
        \ store\n\n---\n\nThis route expires daily at 11:05"
      operationId: "get_loyalty_stores_corporation_id_offers"
      x-alternate-versions:
      - "dev"
      - "legacy"
      - "v1"
  /v1/markets/groups/:
    get:
      tags:
      - "Market"
      summary: "Get item groups"
      description: "Get a list of item groups\n\n---\n\nThis route expires daily at\
        \ 11:05"
      operationId: "get_markets_groups"
      x-alternate-versions:
      - "dev"
      - "legacy"
      - "v1"
  /v1/markets/groups/{market_group_id}/:
    get:
      tags:
      - "Market"
      summary: "Get item group information"
      description: "Get information on an item group\n\n---\n\nThis route expires\
        \ daily at 11:05"
      operationId: "get_markets_groups_market_group_id"
      x-alternate-versions:
      - "dev"
      - "legacy"
      - "v1"
  /v1/markets/prices/:
    get:
      tags:
      - "Market"
      summary: "List market prices"
      description: "Return a list of prices\n\n---\n\nThis route is cached for up\
        \ to 3600 seconds"
      operationId: "get_markets_prices"
      x-alternate-versions:
      - "dev"
      - "legacy"
      - "v1"
      x-cached-seconds: 3600
  /v1/markets/structures/{structure_id}/:
    get:
      tags:
      - "Market"
      summary: "List orders in a structure"
      description: "Return all orders in a structure\n\n---\n\nThis route is cached\
        \ for up to 300 seconds"
      operationId: "get_markets_structures_structure_id"
      security:
      - evesso:
        - "esi-markets.structure_markets.v1"
      x-alternate-versions:
      - "dev"
      - "legacy"
      - "v1"
      x-cached-seconds: 300
  /v1/markets/{region_id}/history/:
    get:
      tags:
      - "Market"
      summary: "List historical market statistics in a region"
      description: "Return a list of historical market statistics for the specified\
        \ type in a region\n\n---\n\nThis route expires daily at 11:05"
      operationId: "get_markets_region_id_history"
      x-alternate-versions:
      - "dev"
      - "legacy"
      - "v1"
  /v1/markets/{region_id}/orders/:
    get:
      tags:
      - "Market"
      summary: "List orders in a region"
      description: "Return a list of orders in a region\n\n---\n\nThis route is cached\
        \ for up to 300 seconds"
      operationId: "get_markets_region_id_orders"
      x-alternate-versions:
      - "dev"
      - "legacy"
      - "v1"
      x-cached-seconds: 300
  /v1/markets/{region_id}/types/:
    get:
      tags:
      - "Market"
      summary: "List type IDs relevant to a market"
      description: "Return a list of type IDs that have active orders in the region,\
        \ for efficient market indexing.\n\n---\n\nThis route is cached for up to\
        \ 600 seconds"
      operationId: "get_markets_region_id_types"
      x-alternate-versions:
      - "dev"
      - "legacy"
      - "v1"
      x-cached-seconds: 600
  /v1/opportunities/groups/:
    get:
      tags:
      - "Opportunities"
      summary: "Get opportunities groups"
      description: "Return a list of opportunities groups\n\n---\n\nThis route expires\
        \ daily at 11:05"
      operationId: "get_opportunities_groups"
      x-alternate-versions:
      - "dev"
      - "legacy"
      - "v1"
  /v1/opportunities/groups/{group_id}/:
    get:
      tags:
      - "Opportunities"
      summary: "Get opportunities group"
      description: "Return information of an opportunities group\n\n---\n\nThis route\
        \ expires daily at 11:05"
      operationId: "get_opportunities_groups_group_id"
      x-alternate-versions:
      - "dev"
      - "legacy"
      - "v1"
  /v1/opportunities/tasks/:
    get:
      tags:
      - "Opportunities"
      summary: "Get opportunities tasks"
      description: "Return a list of opportunities tasks\n\n---\n\nThis route expires\
        \ daily at 11:05"
      operationId: "get_opportunities_tasks"
      x-alternate-versions:
      - "dev"
      - "legacy"
      - "v1"
  /v1/opportunities/tasks/{task_id}/:
    get:
      tags:
      - "Opportunities"
      summary: "Get opportunities task"
      description: "Return information of an opportunities task\n\n---\n\nThis route\
        \ expires daily at 11:05"
      operationId: "get_opportunities_tasks_task_id"
      x-alternate-versions:
      - "dev"
      - "legacy"
      - "v1"
  /v1/route/{origin}/{destination}/:
    get:
      tags:
      - "Routes"
      summary: "Get route"
      description: "Get the systems between origin and destination\n\n---\n\nThis\
        \ route is cached for up to 86400 seconds"
      operationId: "get_route_origin_destination"
      x-alternate-versions:
      - "dev"
      - "legacy"
      - "v1"
      x-cached-seconds: 86400
  /v1/sovereignty/campaigns/:
    get:
      tags:
      - "Sovereignty"
      summary: "List sovereignty campaigns"
      description: "Shows sovereignty data for campaigns.\n\n---\n\nThis route is\
        \ cached for up to 5 seconds"
      operationId: "get_sovereignty_campaigns"
      x-alternate-versions:
      - "dev"
      - "legacy"
      - "v1"
      x-cached-seconds: 5
  /v1/sovereignty/map/:
    get:
      tags:
      - "Sovereignty"
      summary: "List sovereignty of systems"
      description: "Shows sovereignty information for solar systems\n\n---\n\nThis\
        \ route is cached for up to 3600 seconds"
      operationId: "get_sovereignty_map"
      x-alternate-versions:
      - "dev"
      - "legacy"
      - "v1"
      x-cached-seconds: 3600
  /v1/sovereignty/structures/:
    get:
      tags:
      - "Sovereignty"
      summary: "List sovereignty structures"
      description: "Shows sovereignty data for structures.\n\n---\n\nThis route is\
        \ cached for up to 120 seconds"
      operationId: "get_sovereignty_structures"
      x-alternate-versions:
      - "dev"
      - "legacy"
      - "v1"
      x-cached-seconds: 120
  /v1/status/:
    get:
      tags:
      - "Status"
      summary: "Retrieve the uptime and player counts"
      description: "EVE Server status\n\n---\n\nThis route is cached for up to 30\
        \ seconds"
      operationId: "get_status"
      x-alternate-versions:
      - "dev"
      - "legacy"
      - "v1"
      x-cached-seconds: 30
  /v1/ui/openwindow/contract/:
    post:
      tags:
      - "User Interface"
      summary: "Open Contract Window"
      description: "Open the contract window inside the client\n\n---\n"
      operationId: "post_ui_openwindow_contract"
      security:
      - evesso:
        - "esi-ui.open_window.v1"
      x-alternate-versions:
      - "dev"
      - "legacy"
      - "v1"
  /v1/ui/openwindow/information/:
    post:
      tags:
      - "User Interface"
      summary: "Open Information Window"
      description: "Open the information window for a character, corporation or alliance\
        \ inside the client\n\n---\n"
      operationId: "post_ui_openwindow_information"
      security:
      - evesso:
        - "esi-ui.open_window.v1"
      x-alternate-versions:
      - "dev"
      - "legacy"
      - "v1"
  /v1/ui/openwindow/marketdetails/:
    post:
      tags:
      - "User Interface"
      summary: "Open Market Details"
      description: "Open the market details window for a specific typeID inside the\
        \ client\n\n---\n"
      operationId: "post_ui_openwindow_marketdetails"
      security:
      - evesso:
        - "esi-ui.open_window.v1"
      x-alternate-versions:
      - "dev"
      - "legacy"
      - "v1"
  /v1/ui/openwindow/newmail/:
    post:
      tags:
      - "User Interface"
      summary: "Open New Mail Window"
      description: "Open the New Mail window, according to settings from the request\
        \ if applicable\n\n---\n"
      operationId: "post_ui_openwindow_newmail"
      security:
      - evesso:
        - "esi-ui.open_window.v1"
      x-alternate-versions:
      - "dev"
      - "legacy"
      - "v1"
  /v1/universe/ancestries/:
    get:
      tags:
      - "Universe"
      summary: "Get ancestries"
      description: "Get all character ancestries\n\n---\n\nThis route expires daily\
        \ at 11:05"
      operationId: "get_universe_ancestries"
      x-alternate-versions:
      - "dev"
      - "legacy"
      - "v1"
  /v1/universe/asteroid_belts/{asteroid_belt_id}/:
    get:
      tags:
      - "Universe"
      summary: "Get asteroid belt information"
      description: "Get information on an asteroid belt\n\n---\n\nThis route expires\
        \ daily at 11:05"
      operationId: "get_universe_asteroid_belts_asteroid_belt_id"
      x-alternate-versions:
      - "dev"
      - "legacy"
      - "v1"
  /v1/universe/bloodlines/:
    get:
      tags:
      - "Universe"
      summary: "Get bloodlines"
      description: "Get a list of bloodlines\n\n---\n\nThis route expires daily at\
        \ 11:05"
      operationId: "get_universe_bloodlines"
      x-alternate-versions:
      - "dev"
      - "legacy"
      - "v1"
  /v1/universe/categories/:
    get:
      tags:
      - "Universe"
      summary: "Get item categories"
      description: "Get a list of item categories\n\n---\n\nThis route expires daily\
        \ at 11:05"
      operationId: "get_universe_categories"
      x-alternate-versions:
      - "dev"
      - "legacy"
      - "v1"
  /v1/universe/categories/{category_id}/:
    get:
      tags:
      - "Universe"
      summary: "Get item category information"
      description: "Get information of an item category\n\n---\n\nThis route expires\
        \ daily at 11:05"
      operationId: "get_universe_categories_category_id"
      x-alternate-versions:
      - "dev"
      - "legacy"
      - "v1"
  /v1/universe/constellations/:
    get:
      tags:
      - "Universe"
      summary: "Get constellations"
      description: "Get a list of constellations\n\n---\n\nThis route expires daily\
        \ at 11:05"
      operationId: "get_universe_constellations"
      x-alternate-versions:
      - "dev"
      - "legacy"
      - "v1"
  /v1/universe/constellations/{constellation_id}/:
    get:
      tags:
      - "Universe"
      summary: "Get constellation information"
      description: "Get information on a constellation\n\n---\n\nThis route expires\
        \ daily at 11:05"
      operationId: "get_universe_constellations_constellation_id"
      x-alternate-versions:
      - "dev"
      - "legacy"
      - "v1"
  /v1/universe/graphics/:
    get:
      tags:
      - "Universe"
      summary: "Get graphics"
      description: "Get a list of graphics\n\n---\n\nThis route expires daily at 11:05"
      operationId: "get_universe_graphics"
      x-alternate-versions:
      - "dev"
      - "legacy"
      - "v1"
  /v1/universe/graphics/{graphic_id}/:
    get:
      tags:
      - "Universe"
      summary: "Get graphic information"
      description: "Get information on a graphic\n\n---\n\nThis route expires daily\
        \ at 11:05"
      operationId: "get_universe_graphics_graphic_id"
      x-alternate-versions:
      - "dev"
      - "legacy"
      - "v1"
  /v1/universe/groups/:
    get:
      tags:
      - "Universe"
      summary: "Get item groups"
      description: "Get a list of item groups\n\n---\n\nThis route expires daily at\
        \ 11:05"
      operationId: "get_universe_groups"
      x-alternate-versions:
      - "dev"
      - "legacy"
      - "v1"
  /v1/universe/groups/{group_id}/:
    get:
      tags:
      - "Universe"
      summary: "Get item group information"
      description: "Get information on an item group\n\n---\n\nThis route expires\
        \ daily at 11:05"
      operationId: "get_universe_groups_group_id"
      x-alternate-versions:
      - "dev"
      - "legacy"
      - "v1"
  /v1/universe/ids/:
    post:
      tags:
      - "Universe"
      summary: "Bulk names to IDs"
      description: "Resolve a set of names to IDs in the following categories: agents,\
        \ alliances, characters, constellations, corporations factions, inventory_types,\
        \ regions, stations, and systems. Only exact matches will be returned. All\
        \ names searched for are cached for 12 hours.\n\n---\n"
      operationId: "post_universe_ids"
      x-alternate-versions:
      - "dev"
      - "legacy"
      - "v1"
  /v1/universe/moons/{moon_id}/:
    get:
      tags:
      - "Universe"
      summary: "Get moon information"
      description: "Get information on a moon\n\n---\n\nThis route expires daily at\
        \ 11:05"
      operationId: "get_universe_moons_moon_id"
      x-alternate-versions:
      - "dev"
      - "legacy"
      - "v1"
  /v1/universe/planets/{planet_id}/:
    get:
      tags:
      - "Universe"
      summary: "Get planet information"
      description: "Get information on a planet\n\n---\n\nThis route expires daily\
        \ at 11:05"
      operationId: "get_universe_planets_planet_id"
      x-alternate-versions:
      - "dev"
      - "legacy"
      - "v1"
  /v1/universe/races/:
    get:
      tags:
      - "Universe"
      summary: "Get character races"
      description: "Get a list of character races\n\n---\n\nThis route expires daily\
        \ at 11:05"
      operationId: "get_universe_races"
      x-alternate-versions:
      - "dev"
      - "legacy"
      - "v1"
  /v1/universe/regions/:
    get:
      tags:
      - "Universe"
      summary: "Get regions"
      description: "Get a list of regions\n\n---\n\nThis route expires daily at 11:05"
      operationId: "get_universe_regions"
      x-alternate-versions:
      - "dev"
      - "legacy"
      - "v1"
  /v1/universe/regions/{region_id}/:
    get:
      tags:
      - "Universe"
      summary: "Get region information"
      description: "Get information on a region\n\n---\n\nThis route expires daily\
        \ at 11:05"
      operationId: "get_universe_regions_region_id"
      x-alternate-versions:
      - "dev"
      - "legacy"
      - "v1"
  /v1/universe/schematics/{schematic_id}/:
    get:
      tags:
      - "Planetary Interaction"
      summary: "Get schematic information"
      description: "Get information on a planetary factory schematic\n\n---\n\nThis\
        \ route is cached for up to 3600 seconds"
      operationId: "get_universe_schematics_schematic_id"
      x-alternate-versions:
      - "dev"
      - "legacy"
      - "v1"
      x-cached-seconds: 3600
  /v1/universe/stargates/{stargate_id}/:
    get:
      tags:
      - "Universe"
      summary: "Get stargate information"
      description: "Get information on a stargate\n\n---\n\nThis route expires daily\
        \ at 11:05"
      operationId: "get_universe_stargates_stargate_id"
      x-alternate-versions:
      - "dev"
      - "legacy"
      - "v1"
  /v1/universe/stars/{star_id}/:
    get:
      tags:
      - "Universe"
      summary: "Get star information"
      description: "Get information on a star\n\n---\n\nThis route expires daily at\
        \ 11:05"
      operationId: "get_universe_stars_star_id"
      x-alternate-versions:
      - "dev"
      - "legacy"
      - "v1"
  /v1/universe/structures/:
    get:
      tags:
      - "Universe"
      summary: "List all public structures"
      description: "List all public structures\n\n---\n\nThis route is cached for\
        \ up to 3600 seconds"
      operationId: "get_universe_structures"
      x-alternate-versions:
      - "dev"
      - "legacy"
      - "v1"
      x-cached-seconds: 3600
  /v1/universe/structures/{structure_id}/:
    get:
      tags:
      - "Universe"
      summary: "Get structure information"
      description: "Returns information on requested structure, if you are on the\
        \ ACL. Otherwise, returns \"Forbidden\" for all inputs.\n\n---\n\nThis route\
        \ is cached for up to 3600 seconds\n\n---\nWarning: This route has an upgrade\
        \ available.\n\n---\n[Diff of the upcoming changes](https://esi.evetech.net/diff/latest/dev/#GET-/universe/structures/{structure_id}/)"
      operationId: "get_universe_structures_structure_id"
      security:
      - evesso:
        - "esi-universe.read_structures.v1"
      x-alternate-versions:
      - "legacy"
      - "v1"
      x-cached-seconds: 3600
  /v1/universe/system_jumps/:
    get:
      tags:
      - "Universe"
      summary: "Get system jumps"
      description: "Get the number of jumps in solar systems within the last hour\
        \ ending at the timestamp of the Last-Modified header, excluding wormhole\
        \ space. Only systems with jumps will be listed\n\n---\n\nThis route is cached\
        \ for up to 3600 seconds"
      operationId: "get_universe_system_jumps"
      x-alternate-versions:
      - "dev"
      - "legacy"
      - "v1"
      x-cached-seconds: 3600
  /v1/universe/systems/:
    get:
      tags:
      - "Universe"
      summary: "Get solar systems"
      description: "Get a list of solar systems\n\n---\n\nThis route expires daily\
        \ at 11:05"
      operationId: "get_universe_systems"
      x-alternate-versions:
      - "dev"
      - "legacy"
      - "v1"
  /v1/universe/types/:
    get:
      tags:
      - "Universe"
      summary: "Get types"
      description: "Get a list of type ids\n\n---\n\nThis route expires daily at 11:05"
      operationId: "get_universe_types"
      x-alternate-versions:
      - "dev"
      - "legacy"
      - "v1"
  /v1/wars/:
    get:
      tags:
      - "Wars"
      summary: "List wars"
      description: "Return a list of wars\n\n---\n\nThis route is cached for up to\
        \ 3600 seconds"
      operationId: "get_wars"
      x-alternate-versions:
      - "dev"
      - "legacy"
      - "v1"
      x-cached-seconds: 3600
  /v1/wars/{war_id}/:
    get:
      tags:
      - "Wars"
      summary: "Get war information"
      description: "Return details about a war\n\n---\n\nThis route is cached for\
        \ up to 3600 seconds"
      operationId: "get_wars_war_id"
      x-alternate-versions:
      - "dev"
      - "legacy"
      - "v1"
      x-cached-seconds: 3600
  /v1/wars/{war_id}/killmails/:
    get:
      tags:
      - "Wars"
      summary: "List kills for a war"
      description: "Return a list of kills related to a war\n\n---\n\nThis route is\
        \ cached for up to 3600 seconds"
      operationId: "get_wars_war_id_killmails"
      x-alternate-versions:
      - "dev"
      - "legacy"
      - "v1"
      x-cached-seconds: 3600
  /v2/alliances/names/:
    get:
      tags:
      - "Alliance"
      summary: "Get alliance names"
      description: "Resolve a set of alliance IDs to alliance names\n\n---\n\nThis\
        \ route is cached for up to 3600 seconds"
      operationId: "get_alliances_names"
      x-alternate-versions:
      - "dev"
      - "v2"
      x-cached-seconds: 3600
  /v2/alliances/{alliance_id}/contacts/:
    get:
      tags:
      - "Contacts"
      summary: "Get alliance contacts"
      description: "Return contacts of an alliance\n\n---\n\nThis route is cached\
        \ for up to 300 seconds"
      operationId: "get_alliances_alliance_id_contacts"
      security:
      - evesso:
        - "esi-alliances.read_contacts.v1"
      x-alternate-versions:
      - "dev"
      - "v2"
      x-cached-seconds: 300
  /v2/characters/{character_id}/assets/locations/:
    post:
      tags:
      - "Assets"
      summary: "Get character asset locations"
      description: "Return locations for a set of item ids, which you can get from\
        \ character assets endpoint. Coordinates for items in hangars or stations\
        \ are set to (0,0,0)\n\n---\n"
      operationId: "post_characters_character_id_assets_locations"
      security:
      - evesso:
        - "esi-assets.read_assets.v1"
      x-alternate-versions:
      - "dev"
      - "v2"
  /v2/characters/{character_id}/blueprints/:
    get:
      tags:
      - "Character"
      summary: "Get blueprints"
      description: "Return a list of blueprints the character owns\n\n---\n\nThis\
        \ route is cached for up to 3600 seconds"
      operationId: "get_characters_character_id_blueprints"
      security:
      - evesso:
        - "esi-characters.read_blueprints.v1"
      x-alternate-versions:
      - "dev"
      - "v2"
      x-cached-seconds: 3600
  /v2/characters/{character_id}/bookmarks/:
    get:
      tags:
      - "Bookmarks"
      summary: "List bookmarks"
      description: "A list of your character's personal bookmarks\n\n---\n\nThis route\
        \ is cached for up to 3600 seconds"
      operationId: "get_characters_character_id_bookmarks"
      security:
      - evesso:
        - "esi-bookmarks.read_character_bookmarks.v1"
      x-alternate-versions:
      - "dev"
      - "v2"
      x-cached-seconds: 3600
  /v2/characters/{character_id}/bookmarks/folders/:
    get:
      tags:
      - "Bookmarks"
      summary: "List bookmark folders"
      description: "A list of your character's personal bookmark folders\n\n---\n\n\
        This route is cached for up to 3600 seconds"
      operationId: "get_characters_character_id_bookmarks_folders"
      security:
      - evesso:
        - "esi-bookmarks.read_character_bookmarks.v1"
      x-alternate-versions:
      - "dev"
      - "v2"
      x-cached-seconds: 3600
  /v2/characters/{character_id}/contacts/:
    get:
      tags:
      - "Contacts"
      summary: "Get contacts"
      description: "Return contacts of a character\n\n---\n\nThis route is cached\
        \ for up to 300 seconds"
      operationId: "get_characters_character_id_contacts"
      security:
      - evesso:
        - "esi-characters.read_contacts.v1"
      x-alternate-versions:
      - "dev"
      - "v2"
      x-cached-seconds: 300
    post:
      tags:
      - "Contacts"
      summary: "Add contacts"
      description: "Bulk add contacts with same settings\n\n---\n"
      operationId: "post_characters_character_id_contacts"
      security:
      - evesso:
        - "esi-characters.write_contacts.v1"
      x-alternate-versions:
      - "dev"
      - "v2"
    put:
      tags:
      - "Contacts"
      summary: "Edit contacts"
      description: "Bulk edit contacts with same settings\n\n---\n"
      operationId: "put_characters_character_id_contacts"
      security:
      - evesso:
        - "esi-characters.write_contacts.v1"
      x-alternate-versions:
      - "dev"
      - "v2"
    delete:
      tags:
      - "Contacts"
      summary: "Delete contacts"
      description: "Bulk delete contacts\n\n---\n"
      operationId: "delete_characters_character_id_contacts"
      security:
      - evesso:
        - "esi-characters.write_contacts.v1"
      x-alternate-versions:
      - "dev"
      - "v2"
  /v2/characters/{character_id}/mail/labels/:
    post:
      tags:
      - "Mail"
      summary: "Create a mail label"
      description: "Create a mail label\n\n---\n"
      operationId: "post_characters_character_id_mail_labels"
      security:
      - evesso:
        - "esi-mail.organize_mail.v1"
      x-alternate-versions:
      - "dev"
      - "legacy"
      - "v2"
  /v2/characters/{character_id}/notifications/:
    get:
      tags:
      - "Character"
      summary: "Get character notifications"
      description: "Return character notifications\n\n---\n\nThis route is cached\
        \ for up to 600 seconds"
      operationId: "get_characters_character_id_notifications"
      security:
      - evesso:
        - "esi-characters.read_notifications.v1"
      x-alternate-versions:
      - "dev"
      - "v2"
      x-cached-seconds: 600
  /v2/characters/{character_id}/online/:
    get:
      tags:
      - "Location"
      summary: "Get character online"
      description: "Checks if the character is currently online\n\n---\n\nThis route\
        \ is cached for up to 60 seconds"
      operationId: "get_characters_character_id_online"
      security:
      - evesso:
        - "esi-location.read_online.v1"
      x-alternate-versions:
      - "dev"
      - "v2"
      x-cached-seconds: 60
  /v2/characters/{character_id}/orders/:
    get:
      tags:
      - "Market"
      summary: "List open orders from a character"
      description: "List open market orders placed by a character\n\n---\n\nThis route\
        \ is cached for up to 1200 seconds"
      operationId: "get_characters_character_id_orders"
      security:
      - evesso:
        - "esi-markets.read_character_orders.v1"
      x-alternate-versions:
      - "dev"
      - "v2"
      x-cached-seconds: 1200
  /v2/characters/{character_id}/portrait/:
    get:
      tags:
      - "Character"
      summary: "Get character portraits"
      description: "Get portrait urls for a character\n\n---\n\nThis route is cached\
        \ for up to 3600 seconds"
      operationId: "get_characters_character_id_portrait"
      x-alternate-versions:
      - "dev"
      - "v2"
      x-cached-seconds: 3600
  /v2/characters/{character_id}/roles/:
    get:
      tags:
      - "Character"
      summary: "Get character corporation roles"
      description: "Returns a character's corporation roles\n\n---\n\nThis route is\
        \ cached for up to 3600 seconds"
      operationId: "get_characters_character_id_roles"
      security:
      - evesso:
        - "esi-characters.read_corporation_roles.v1"
      x-alternate-versions:
      - "dev"
      - "v2"
      x-cached-seconds: 3600
  /v2/characters/{character_id}/skillqueue/:
    get:
      tags:
      - "Skills"
      summary: "Get character's skill queue"
      description: "List the configured skill queue for the given character\n\n---\n\
        \nThis route is cached for up to 120 seconds"
      operationId: "get_characters_character_id_skillqueue"
      security:
      - evesso:
        - "esi-skills.read_skillqueue.v1"
      x-alternate-versions:
      - "dev"
      - "legacy"
      - "v2"
      x-cached-seconds: 120
  /v2/characters/{character_id}/stats/:
    get:
      tags:
      - "Character"
      summary: "Yearly aggregate stats"
      description: "Returns aggregate yearly stats for a character\n\n---\n\nThis\
        \ route is cached for up to 86400 seconds"
      operationId: "get_characters_character_id_stats"
      security:
      - evesso:
        - "esi-characterstats.read.v1"
      x-alternate-versions:
      - "dev"
      - "v2"
      x-cached-seconds: 86400
  /v2/corporations/{corporation_id}/alliancehistory/:
    get:
      tags:
      - "Corporation"
      summary: "Get alliance history"
      description: "Get a list of all the alliances a corporation has been a member\
        \ of\n\n---\n\nThis route is cached for up to 3600 seconds"
      operationId: "get_corporations_corporation_id_alliancehistory"
      x-alternate-versions:
      - "dev"
      - "v2"
      x-cached-seconds: 3600
  /v2/corporations/{corporation_id}/assets/locations/:
    post:
      tags:
      - "Assets"
      summary: "Get corporation asset locations"
      description: "Return locations for a set of item ids, which you can get from\
        \ corporation assets endpoint. Coordinates for items in hangars or stations\
        \ are set to (0,0,0)\n\n---\n\nRequires one of the following EVE corporation\
        \ role(s): Director"
      operationId: "post_corporations_corporation_id_assets_locations"
      security:
      - evesso:
        - "esi-assets.read_corporation_assets.v1"
      x-alternate-versions:
      - "dev"
      - "v2"
      x-required-roles:
      - "Director"
  /v2/corporations/{corporation_id}/blueprints/:
    get:
      tags:
      - "Corporation"
      summary: "Get corporation blueprints"
      description: "Returns a list of blueprints the corporation owns\n\n---\n\nThis\
        \ route is cached for up to 3600 seconds\n\n---\nRequires one of the following\
        \ EVE corporation role(s): Director"
      operationId: "get_corporations_corporation_id_blueprints"
      security:
      - evesso:
        - "esi-corporations.read_blueprints.v1"
      x-alternate-versions:
      - "dev"
      - "v2"
      x-cached-seconds: 3600
      x-required-roles:
      - "Director"
  /v2/corporations/{corporation_id}/contacts/:
    get:
      tags:
      - "Contacts"
      summary: "Get corporation contacts"
      description: "Return contacts of a corporation\n\n---\n\nThis route is cached\
        \ for up to 300 seconds"
      operationId: "get_corporations_corporation_id_contacts"
      security:
      - evesso:
        - "esi-corporations.read_contacts.v1"
      x-alternate-versions:
      - "dev"
      - "v2"
      x-cached-seconds: 300
      x-required-roles: []
  /v2/corporations/{corporation_id}/containers/logs/:
    get:
      tags:
      - "Corporation"
      summary: "Get all corporation ALSC logs"
      description: "Returns logs recorded in the past seven days from all audit log\
        \ secure containers (ALSC) owned by a given corporation\n\n---\n\nThis route\
        \ is cached for up to 600 seconds\n\n---\nRequires one of the following EVE\
        \ corporation role(s): Director"
      operationId: "get_corporations_corporation_id_containers_logs"
      security:
      - evesso:
        - "esi-corporations.read_container_logs.v1"
      x-alternate-versions:
      - "dev"
      - "v2"
      x-cached-seconds: 600
      x-required-roles:
      - "Director"
  /v2/corporations/{corporation_id}/orders/:
    get:
      tags:
      - "Market"
      summary: "List open orders from a corporation"
      description: "List open market orders placed on behalf of a corporation\n\n\
        ---\n\nThis route is cached for up to 1200 seconds\n\n---\nRequires one of\
        \ the following EVE corporation role(s): Accountant, Trader\n\n---\nWarning:\
        \ This route has an upgrade available.\n\n---\n[Diff of the upcoming changes](https://esi.evetech.net/diff/latest/dev/#GET-/corporations/{corporation_id}/orders/)"
      operationId: "get_corporations_corporation_id_orders"
      security:
      - evesso:
        - "esi-markets.read_corporation_orders.v1"
      x-alternate-versions:
      - "v2"
      x-cached-seconds: 1200
      x-required-roles:
      - "Accountant"
      - "Trader"
  /v2/corporations/{corporation_id}/structures/:
    get:
      tags:
      - "Corporation"
      summary: "Get corporation structures"
      description: "Get a list of corporation structures. This route's version includes\
        \ the changes to structures detailed in this blog: https://www.eveonline.com/article/upwell-2.0-structures-changes-coming-on-february-13th\n\
        \n---\n\nThis route is cached for up to 3600 seconds\n\n---\nRequires one\
        \ of the following EVE corporation role(s): StationManager"
      operationId: "get_corporations_corporation_id_structures"
      security:
      - evesso:
        - "esi-corporations.read_structures.v1"
      x-alternate-versions:
      - "dev"
      - "v2"
      x-cached-seconds: 3600
      x-required-roles:
      - "StationManager"
  /v2/dogma/effects/{effect_id}/:
    get:
      tags:
      - "Dogma"
      summary: "Get effect information"
      description: "Get information on a dogma effect\n\n---\n\nThis route expires\
        \ daily at 11:05"
      operationId: "get_dogma_effects_effect_id"
      x-alternate-versions:
      - "dev"
      - "v2"
  /v2/search/:
    get:
      tags:
      - "Search"
      summary: "Search on a string"
      description: "Search for entities that match a given sub-string.\n\n---\n\n\
        This route is cached for up to 3600 seconds"
      operationId: "get_search"
      x-alternate-versions:
      - "dev"
      - "v2"
      x-cached-seconds: 3600
  /v2/ui/autopilot/waypoint/:
    post:
      tags:
      - "User Interface"
      summary: "Set Autopilot Waypoint"
      description: "Set a solar system as autopilot waypoint\n\n---\n"
      operationId: "post_ui_autopilot_waypoint"
      security:
      - evesso:
        - "esi-ui.write_waypoint.v1"
      x-alternate-versions:
      - "dev"
      - "v2"
  /v2/universe/factions/:
    get:
      tags:
      - "Universe"
      summary: "Get factions"
      description: "Get a list of factions\n\n---\n\nThis route expires daily at 11:05"
      operationId: "get_universe_factions"
      x-alternate-versions:
      - "dev"
      - "v2"
  /v2/universe/names/:
    post:
      tags:
      - "Universe"
      summary: "Get names and categories for a set of ID's"
      description: "Resolve a set of IDs to names and categories. Supported ID's for\
        \ resolving are: Characters, Corporations, Alliances, Stations, Solar Systems,\
        \ Constellations, Regions, Types.\n\n---\n"
      operationId: "post_universe_names"
      x-alternate-versions:
      - "dev"
      - "v2"
  /v2/universe/stations/{station_id}/:
    get:
      tags:
      - "Universe"
      summary: "Get station information"
      description: "Get information on a station\n\n---\n\nThis route expires daily\
        \ at 11:05"
      operationId: "get_universe_stations_station_id"
      x-alternate-versions:
      - "dev"
      - "v2"
  /v2/universe/system_kills/:
    get:
      tags:
      - "Universe"
      summary: "Get system kills"
      description: "Get the number of ship, pod and NPC kills per solar system within\
        \ the last hour ending at the timestamp of the Last-Modified header, excluding\
        \ wormhole space. Only systems with kills will be listed\n\n---\n\nThis route\
        \ is cached for up to 3600 seconds"
      operationId: "get_universe_system_kills"
      x-alternate-versions:
      - "dev"
      - "v2"
      x-cached-seconds: 3600
  /v3/alliances/{alliance_id}/:
    get:
      tags:
      - "Alliance"
      summary: "Get alliance information"
      description: "Public information about an alliance\n\n---\n\nThis route is cached\
        \ for up to 3600 seconds"
      operationId: "get_alliances_alliance_id"
      x-alternate-versions:
      - "dev"
      - "v3"
      x-cached-seconds: 3600
  /v3/characters/{character_id}/assets/:
    get:
      tags:
      - "Assets"
      summary: "Get character assets"
      description: "Return a list of the characters assets\n\n---\n\nThis route is\
        \ cached for up to 3600 seconds"
      operationId: "get_characters_character_id_assets"
      security:
      - evesso:
        - "esi-assets.read_assets.v1"
      x-alternate-versions:
      - "dev"
      - "v3"
      x-cached-seconds: 3600
  /v3/characters/{character_id}/calendar/{event_id}/:
    get:
      tags:
      - "Calendar"
      summary: "Get an event"
      description: "Get all the information for a specific event\n\n---\n\nThis route\
        \ is cached for up to 5 seconds"
      operationId: "get_characters_character_id_calendar_event_id"
      security:
      - evesso:
        - "esi-calendar.read_calendar_events.v1"
      x-alternate-versions:
      - "dev"
      - "v3"
      x-cached-seconds: 5
    put:
      tags:
      - "Calendar"
      summary: "Respond to an event"
      description: "Set your response status to an event\n\n---\n"
      operationId: "put_characters_character_id_calendar_event_id"
      security:
      - evesso:
        - "esi-calendar.respond_calendar_events.v1"
      x-alternate-versions:
      - "dev"
      - "v3"
  /v3/characters/{character_id}/clones/:
    get:
      tags:
      - "Clones"
      summary: "Get clones"
      description: "A list of the character's clones\n\n---\n\nThis route is cached\
        \ for up to 120 seconds"
      operationId: "get_characters_character_id_clones"
      security:
      - evesso:
        - "esi-clones.read_clones.v1"
      x-alternate-versions:
      - "dev"
      - "v3"
      x-cached-seconds: 120
  /v3/characters/{character_id}/mail/labels/:
    get:
      tags:
      - "Mail"
      summary: "Get mail labels and unread counts"
      description: "Return a list of the users mail labels, unread counts for each\
        \ label and a total unread count.\n\n---\n\nThis route is cached for up to\
        \ 30 seconds"
      operationId: "get_characters_character_id_mail_labels"
      security:
      - evesso:
        - "esi-mail.read_mail.v1"
      x-alternate-versions:
      - "dev"
      - "v3"
      x-cached-seconds: 30
  /v3/characters/{character_id}/planets/{planet_id}/:
    get:
      tags:
      - "Planetary Interaction"
      summary: "Get colony layout"
      description: "Returns full details on the layout of a single planetary colony,\
        \ including links, pins and routes. Note: Planetary information is only recalculated\
        \ when the colony is viewed through the client. Information will not update\
        \ until this criteria is met.\n\n---\n\nThis route is cached for up to 600\
        \ seconds"
      operationId: "get_characters_character_id_planets_planet_id"
      security:
      - evesso:
        - "esi-planets.manage_planets.v1"
      x-alternate-versions:
      - "dev"
      - "v3"
      x-cached-seconds: 600
  /v3/characters/{character_id}/search/:
    get:
      tags:
      - "Search"
      summary: "Search on a string"
      description: "Search for entities that match a given sub-string.\n\n---\n\n\
        This route is cached for up to 3600 seconds"
      operationId: "get_characters_character_id_search"
      security:
      - evesso:
        - "esi-search.search_structures.v1"
      x-alternate-versions:
      - "dev"
      - "v3"
      x-cached-seconds: 3600
  /v3/corporations/{corporation_id}/assets/:
    get:
      tags:
      - "Assets"
      summary: "Get corporation assets"
      description: "Return a list of the corporation assets\n\n---\n\nThis route is\
        \ cached for up to 3600 seconds\n\n---\nRequires one of the following EVE\
        \ corporation role(s): Director"
      operationId: "get_corporations_corporation_id_assets"
      security:
      - evesso:
        - "esi-assets.read_corporation_assets.v1"
      x-alternate-versions:
      - "dev"
      - "v3"
      x-cached-seconds: 3600
      x-required-roles:
      - "Director"
  /v3/corporations/{corporation_id}/members/:
    get:
      tags:
      - "Corporation"
      summary: "Get corporation members"
      description: "Return the current member list of a corporation, the token's character\
        \ need to be a member of the corporation.\n\n---\n\nThis route is cached for\
        \ up to 3600 seconds"
      operationId: "get_corporations_corporation_id_members"
      security:
      - evesso:
        - "esi-corporations.read_corporation_membership.v1"
      x-alternate-versions:
      - "dev"
      - "v3"
      x-cached-seconds: 3600
  /v3/corporations/{corporation_id}/wallets/{division}/journal/:
    get:
      tags:
      - "Wallet"
      summary: "Get corporation wallet journal"
      description: "Retrieve the given corporation's wallet journal for the given\
        \ division going 30 days back\n\n---\n\nThis route is cached for up to 3600\
        \ seconds\n\n---\nRequires one of the following EVE corporation role(s): Accountant,\
        \ Junior_Accountant"
      operationId: "get_corporations_corporation_id_wallets_division_journal"
      security:
      - evesso:
        - "esi-wallet.read_corporation_wallets.v1"
      x-alternate-versions:
      - "dev"
      - "legacy"
      - "v3"
      x-cached-seconds: 3600
      x-required-roles:
      - "Accountant"
      - "Junior_Accountant"
  /v3/universe/systems/{system_id}/:
    get:
      tags:
      - "Universe"
      summary: "Get solar system information"
      description: "Get information on a solar system. NOTE: This route does not work\
        \ with abyssal systems.\n\n---\n\nThis route expires daily at 11:05\n\n---\n\
        Warning: This route has an upgrade available.\n\n---\n[Diff of the upcoming\
        \ changes](https://esi.evetech.net/diff/latest/dev/#GET-/universe/systems/{system_id}/)"
      operationId: "get_universe_systems_system_id"
      x-alternate-versions:
      - "v3"
  /v3/universe/types/{type_id}/:
    get:
      tags:
      - "Universe"
      summary: "Get type information"
      description: "Get information on a type\n\n---\n\nThis route expires daily at\
        \ 11:05"
      operationId: "get_universe_types_type_id"
      x-alternate-versions:
      - "dev"
      - "v3"
  /v4/characters/{character_id}/:
    get:
      tags:
      - "Character"
      summary: "Get character's public information"
      description: "Public information about a character\n\n---\n\nThis route is cached\
        \ for up to 3600 seconds"
      operationId: "get_characters_character_id"
      x-alternate-versions:
      - "dev"
      - "v4"
      x-cached-seconds: 3600
  /v4/characters/{character_id}/cspa/:
    post:
      tags:
      - "Character"
      summary: "Calculate a CSPA charge cost"
      description: "Takes a source character ID in the url and a set of target character\
        \ ID's in the body, returns a CSPA charge cost\n\n---\n"
      operationId: "post_characters_character_id_cspa"
      security:
      - evesso:
        - "esi-characters.read_contacts.v1"
      x-alternate-versions:
      - "dev"
      - "v4"
  /v4/characters/{character_id}/skills/:
    get:
      tags:
      - "Skills"
      summary: "Get character skills"
      description: "List all trained skills for the given character\n\n---\n\nThis\
        \ route is cached for up to 120 seconds"
      operationId: "get_characters_character_id_skills"
      security:
      - evesso:
        - "esi-skills.read_skills.v1"
      x-alternate-versions:
      - "dev"
      - "v4"
      x-cached-seconds: 120
  /v4/characters/{character_id}/wallet/journal/:
    get:
      tags:
      - "Wallet"
      summary: "Get character wallet journal"
      description: "Retrieve the given character's wallet journal going 30 days back\n\
        \n---\n\nThis route is cached for up to 3600 seconds"
      operationId: "get_characters_character_id_wallet_journal"
      security:
      - evesso:
        - "esi-wallet.read_character_wallet.v1"
      x-alternate-versions:
      - "dev"
      - "legacy"
      - "v4"
      x-cached-seconds: 3600
  /v4/corporations/{corporation_id}/:
    get:
      tags:
      - "Corporation"
      summary: "Get corporation information"
      description: "Public information about a corporation\n\n---\n\nThis route is\
        \ cached for up to 3600 seconds"
      operationId: "get_corporations_corporation_id"
      x-alternate-versions:
      - "dev"
      - "v4"
      x-cached-seconds: 3600
securityDefinitions:
  evesso:
    type: "oauth2"
    authorizationUrl: "https://login.eveonline.com/oauth/authorize"
    flow: "implicit"
    scopes:
      esi-alliances.read_contacts.v1: "EVE SSO scope esi-alliances.read_contacts.v1"
      esi-assets.read_assets.v1: "EVE SSO scope esi-assets.read_assets.v1"
      esi-assets.read_corporation_assets.v1: "EVE SSO scope esi-assets.read_corporation_assets.v1"
      esi-bookmarks.read_character_bookmarks.v1: "EVE SSO scope esi-bookmarks.read_character_bookmarks.v1"
      esi-bookmarks.read_corporation_bookmarks.v1: "EVE SSO scope esi-bookmarks.read_corporation_bookmarks.v1"
      esi-calendar.read_calendar_events.v1: "EVE SSO scope esi-calendar.read_calendar_events.v1"
      esi-calendar.respond_calendar_events.v1: "EVE SSO scope esi-calendar.respond_calendar_events.v1"
      esi-characters.read_agents_research.v1: "EVE SSO scope esi-characters.read_agents_research.v1"
      esi-characters.read_blueprints.v1: "EVE SSO scope esi-characters.read_blueprints.v1"
      esi-characters.read_contacts.v1: "EVE SSO scope esi-characters.read_contacts.v1"
      esi-characters.read_corporation_roles.v1: "EVE SSO scope esi-characters.read_corporation_roles.v1"
      esi-characters.read_fatigue.v1: "EVE SSO scope esi-characters.read_fatigue.v1"
      esi-characters.read_fw_stats.v1: "EVE SSO scope esi-characters.read_fw_stats.v1"
      esi-characters.read_loyalty.v1: "EVE SSO scope esi-characters.read_loyalty.v1"
      esi-characters.read_medals.v1: "EVE SSO scope esi-characters.read_medals.v1"
      esi-characters.read_notifications.v1: "EVE SSO scope esi-characters.read_notifications.v1"
      esi-characters.read_opportunities.v1: "EVE SSO scope esi-characters.read_opportunities.v1"
      esi-characters.read_standings.v1: "EVE SSO scope esi-characters.read_standings.v1"
      esi-characters.read_titles.v1: "EVE SSO scope esi-characters.read_titles.v1"
      esi-characters.write_contacts.v1: "EVE SSO scope esi-characters.write_contacts.v1"
      esi-characterstats.read.v1: "EVE SSO scope esi-characterstats.read.v1"
      esi-clones.read_clones.v1: "EVE SSO scope esi-clones.read_clones.v1"
      esi-clones.read_implants.v1: "EVE SSO scope esi-clones.read_implants.v1"
      esi-contracts.read_character_contracts.v1: "EVE SSO scope esi-contracts.read_character_contracts.v1"
      esi-contracts.read_corporation_contracts.v1: "EVE SSO scope esi-contracts.read_corporation_contracts.v1"
      esi-corporations.read_blueprints.v1: "EVE SSO scope esi-corporations.read_blueprints.v1"
      esi-corporations.read_contacts.v1: "EVE SSO scope esi-corporations.read_contacts.v1"
      esi-corporations.read_container_logs.v1: "EVE SSO scope esi-corporations.read_container_logs.v1"
      esi-corporations.read_corporation_membership.v1: "EVE SSO scope esi-corporations.read_corporation_membership.v1"
      esi-corporations.read_divisions.v1: "EVE SSO scope esi-corporations.read_divisions.v1"
      esi-corporations.read_facilities.v1: "EVE SSO scope esi-corporations.read_facilities.v1"
      esi-corporations.read_fw_stats.v1: "EVE SSO scope esi-corporations.read_fw_stats.v1"
      esi-corporations.read_medals.v1: "EVE SSO scope esi-corporations.read_medals.v1"
      esi-corporations.read_outposts.v1: "EVE SSO scope esi-corporations.read_outposts.v1"
      esi-corporations.read_standings.v1: "EVE SSO scope esi-corporations.read_standings.v1"
      esi-corporations.read_starbases.v1: "EVE SSO scope esi-corporations.read_starbases.v1"
      esi-corporations.read_structures.v1: "EVE SSO scope esi-corporations.read_structures.v1"
      esi-corporations.read_titles.v1: "EVE SSO scope esi-corporations.read_titles.v1"
      esi-corporations.track_members.v1: "EVE SSO scope esi-corporations.track_members.v1"
      esi-fittings.read_fittings.v1: "EVE SSO scope esi-fittings.read_fittings.v1"
      esi-fittings.write_fittings.v1: "EVE SSO scope esi-fittings.write_fittings.v1"
      esi-fleets.read_fleet.v1: "EVE SSO scope esi-fleets.read_fleet.v1"
      esi-fleets.write_fleet.v1: "EVE SSO scope esi-fleets.write_fleet.v1"
      esi-industry.read_character_jobs.v1: "EVE SSO scope esi-industry.read_character_jobs.v1"
      esi-industry.read_character_mining.v1: "EVE SSO scope esi-industry.read_character_mining.v1"
      esi-industry.read_corporation_jobs.v1: "EVE SSO scope esi-industry.read_corporation_jobs.v1"
      esi-industry.read_corporation_mining.v1: "EVE SSO scope esi-industry.read_corporation_mining.v1"
      esi-killmails.read_corporation_killmails.v1: "EVE SSO scope esi-killmails.read_corporation_killmails.v1"
      esi-killmails.read_killmails.v1: "EVE SSO scope esi-killmails.read_killmails.v1"
      esi-location.read_location.v1: "EVE SSO scope esi-location.read_location.v1"
      esi-location.read_online.v1: "EVE SSO scope esi-location.read_online.v1"
      esi-location.read_ship_type.v1: "EVE SSO scope esi-location.read_ship_type.v1"
      esi-mail.organize_mail.v1: "EVE SSO scope esi-mail.organize_mail.v1"
      esi-mail.read_mail.v1: "EVE SSO scope esi-mail.read_mail.v1"
      esi-mail.send_mail.v1: "EVE SSO scope esi-mail.send_mail.v1"
      esi-markets.read_character_orders.v1: "EVE SSO scope esi-markets.read_character_orders.v1"
      esi-markets.read_corporation_orders.v1: "EVE SSO scope esi-markets.read_corporation_orders.v1"
      esi-markets.structure_markets.v1: "EVE SSO scope esi-markets.structure_markets.v1"
      esi-planets.manage_planets.v1: "EVE SSO scope esi-planets.manage_planets.v1"
      esi-planets.read_customs_offices.v1: "EVE SSO scope esi-planets.read_customs_offices.v1"
      esi-search.search_structures.v1: "EVE SSO scope esi-search.search_structures.v1"
      esi-skills.read_skillqueue.v1: "EVE SSO scope esi-skills.read_skillqueue.v1"
      esi-skills.read_skills.v1: "EVE SSO scope esi-skills.read_skills.v1"
      esi-ui.open_window.v1: "EVE SSO scope esi-ui.open_window.v1"
      esi-ui.write_waypoint.v1: "EVE SSO scope esi-ui.write_waypoint.v1"
      esi-universe.read_structures.v1: "EVE SSO scope esi-universe.read_structures.v1"
      esi-wallet.read_character_wallet.v1: "EVE SSO scope esi-wallet.read_character_wallet.v1"
      esi-wallet.read_corporation_wallets.v1: "EVE SSO scope esi-wallet.read_corporation_wallets.v1"