/*
 * EVE Swagger Interface
 *
 * An OpenAPI for EVE Online
 *
 * OpenAPI spec version: 0.4.3.dev6
 *
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package goesiv1

/* 200 ok object */
type GetCharactersCharacterIdPortraitOk struct {
	Var128x128 string `json:"128x128,omitempty"` /* 128x128 string */
	Var256x256 string `json:"256x256,omitempty"` /* 256x256 string */
	Var512x512 string `json:"512x512,omitempty"` /* 512x512 string */
	Var64x64   string `json:"64x64,omitempty"`   /* 64x64 string */
}
