// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package goesiv1

import (
	json "encoding/json"

	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjson8222f131DecodeGithubComAntihaxGoesiV1(in *jlexer.Lexer, out *GetCorporationsCorporationIdAlliancehistoryAllianceList) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		in.Skip()
		*out = nil
	} else {
		in.Delim('[')
		if *out == nil {
			if !in.IsDelim(']') {
				*out = make(GetCorporationsCorporationIdAlliancehistoryAllianceList, 0, 8)
			} else {
				*out = GetCorporationsCorporationIdAlliancehistoryAllianceList{}
			}
		} else {
			*out = (*out)[:0]
		}
		for !in.IsDelim(']') {
			var v1 GetCorporationsCorporationIdAlliancehistoryAlliance
			(v1).UnmarshalEasyJSON(in)
			*out = append(*out, v1)
			in.WantComma()
		}
		in.Delim(']')
	}
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson8222f131EncodeGithubComAntihaxGoesiV1(out *jwriter.Writer, in GetCorporationsCorporationIdAlliancehistoryAllianceList) {
	if in == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
		out.RawString("null")
	} else {
		out.RawByte('[')
		for v2, v3 := range in {
			if v2 > 0 {
				out.RawByte(',')
			}
			(v3).MarshalEasyJSON(out)
		}
		out.RawByte(']')
	}
}

// MarshalJSON supports json.Marshaler interface
func (v GetCorporationsCorporationIdAlliancehistoryAllianceList) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson8222f131EncodeGithubComAntihaxGoesiV1(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v GetCorporationsCorporationIdAlliancehistoryAllianceList) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson8222f131EncodeGithubComAntihaxGoesiV1(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *GetCorporationsCorporationIdAlliancehistoryAllianceList) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson8222f131DecodeGithubComAntihaxGoesiV1(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *GetCorporationsCorporationIdAlliancehistoryAllianceList) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson8222f131DecodeGithubComAntihaxGoesiV1(l, v)
}
func easyjson8222f131DecodeGithubComAntihaxGoesiV11(in *jlexer.Lexer, out *GetCorporationsCorporationIdAlliancehistoryAlliance) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeString()
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "alliance_id":
			out.AllianceId = int32(in.Int32())
		case "is_deleted":
			out.IsDeleted = bool(in.Bool())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson8222f131EncodeGithubComAntihaxGoesiV11(out *jwriter.Writer, in GetCorporationsCorporationIdAlliancehistoryAlliance) {
	out.RawByte('{')
	first := true
	_ = first
	if in.AllianceId != 0 {
		if !first {
			out.RawByte(',')
		}
		first = false
		out.RawString("\"alliance_id\":")
		out.Int32(int32(in.AllianceId))
	}
	if in.IsDeleted {
		if !first {
			out.RawByte(',')
		}
		first = false
		out.RawString("\"is_deleted\":")
		out.Bool(bool(in.IsDeleted))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v GetCorporationsCorporationIdAlliancehistoryAlliance) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson8222f131EncodeGithubComAntihaxGoesiV11(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v GetCorporationsCorporationIdAlliancehistoryAlliance) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson8222f131EncodeGithubComAntihaxGoesiV11(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *GetCorporationsCorporationIdAlliancehistoryAlliance) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson8222f131DecodeGithubComAntihaxGoesiV11(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *GetCorporationsCorporationIdAlliancehistoryAlliance) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson8222f131DecodeGithubComAntihaxGoesiV11(l, v)
}
