package goesi

const (
	ScopeCharacterAccountRead            = "characterAccountRead"
	ScopeCharacterAssetsRead             = "characterAssetsRead"
	ScopeCharacterBookmarksRead          = "characterBookmarksRead"
	ScopeCharacterCalendarRead           = "characterCalendarRead"
	ScopeCharacterChatChannelsRead       = "characterChatChannelsRead"
	ScopeCharacterClonesRead             = "characterClonesRead"
	ScopeCharacterContactsRead           = "characterContactsRead"
	ScopeCharacterContactsWrite          = "characterContactsWrite"
	ScopeCharacterContractsRead          = "characterContractsRead"
	ScopeCharacterFactionalWarfareRead   = "characterFactionalWarfareRead"
	ScopeCharacterFittingsRead           = "characterFittingsRead"
	ScopeCharacterFittingsWrite          = "characterFittingsWrite"
	ScopeCharacterIndustryJobsRead       = "characterIndustryJobsRead"
	ScopeCharacterKillsRead              = "characterKillsRead"
	ScopeCharacterLocationRead           = "characterLocationRead"
	ScopeCharacterLoyaltyPointsRead      = "characterLoyaltyPointsRead"
	ScopeCharacterMailRead               = "characterMailRead"
	ScopeCharacterMarketOrdersRead       = "characterMarketOrdersRead"
	ScopeCharacterMedalsRead             = "characterMedalsRead"
	ScopeCharacterNavigationWrite        = "characterNavigationWrite"
	ScopeCharacterNotificationsRead      = "characterNotificationsRead"
	ScopeCharacterOpportunitiesRead      = "characterOpportunitiesRead"
	ScopeCharacterResearchRead           = "characterResearchRead"
	ScopeCharacterSkillsRead             = "characterSkillsRead"
	ScopeCharacterStatsRead              = "characterStatsRead"
	ScopeCharacterWalletRead             = "characterWalletRead"
	ScopeCorporationAssetsRead           = "corporationAssetsRead"
	ScopeCorporationBookmarksRead        = "corporationBookmarksRead"
	ScopeCorporationContactsRead         = "corporationContactsRead"
	ScopeCorporationContractsRead        = "corporationContractsRead"
	ScopeCorporationFactionalWarfareRead = "corporationFactionalWarfareRead"
	ScopeCorporationIndustryJobsRead     = "corporationIndustryJobsRead"
	ScopeCorporationKillsRead            = "corporationKillsRead"
	ScopeCorporationMarketOrdersRead     = "corporationMarketOrdersRead"
	ScopeCorporationMedalsRead           = "corporationMedalsRead"
	ScopeCorporationMembersRead          = "corporationMembersRead"
	ScopeCorporationShareholdersRead     = "corporationShareholdersRead"
	ScopeCorporationStructuresRead       = "corporationStructuresRead"
	ScopeCorporationWalletRead           = "corporationWalletRead"
	ScopeFleetRead                       = "fleetRead"
	ScopeFleetWrite                      = "fleetWrite"
	ScopeRemoteClientUI                  = "remoteClientUI"
	ScopeStructureVulnUpdate             = "structureVulnUpdate"
)
