// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package goesiv2

import (
	json "encoding/json"

	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjson3813a42fDecodeGithubComAntihaxGoesiV2(in *jlexer.Lexer, out *GetCharactersCharacterIdMailLabels200OkList) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		in.Skip()
		*out = nil
	} else {
		in.Delim('[')
		if *out == nil {
			if !in.IsDelim(']') {
				*out = make(GetCharactersCharacterIdMailLabels200OkList, 0, 1)
			} else {
				*out = GetCharactersCharacterIdMailLabels200OkList{}
			}
		} else {
			*out = (*out)[:0]
		}
		for !in.IsDelim(']') {
			var v1 GetCharactersCharacterIdMailLabels200Ok
			(v1).UnmarshalEasyJSON(in)
			*out = append(*out, v1)
			in.WantComma()
		}
		in.Delim(']')
	}
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson3813a42fEncodeGithubComAntihaxGoesiV2(out *jwriter.Writer, in GetCharactersCharacterIdMailLabels200OkList) {
	if in == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
		out.RawString("null")
	} else {
		out.RawByte('[')
		for v2, v3 := range in {
			if v2 > 0 {
				out.RawByte(',')
			}
			(v3).MarshalEasyJSON(out)
		}
		out.RawByte(']')
	}
}

// MarshalJSON supports json.Marshaler interface
func (v GetCharactersCharacterIdMailLabels200OkList) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson3813a42fEncodeGithubComAntihaxGoesiV2(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v GetCharactersCharacterIdMailLabels200OkList) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson3813a42fEncodeGithubComAntihaxGoesiV2(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *GetCharactersCharacterIdMailLabels200OkList) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson3813a42fDecodeGithubComAntihaxGoesiV2(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *GetCharactersCharacterIdMailLabels200OkList) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson3813a42fDecodeGithubComAntihaxGoesiV2(l, v)
}
func easyjson3813a42fDecodeGithubComAntihaxGoesiV21(in *jlexer.Lexer, out *GetCharactersCharacterIdMailLabels200Ok) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeString()
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "color":
			out.Color = string(in.String())
		case "label_id":
			out.LabelId = int32(in.Int32())
		case "name":
			out.Name = string(in.String())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson3813a42fEncodeGithubComAntihaxGoesiV21(out *jwriter.Writer, in GetCharactersCharacterIdMailLabels200Ok) {
	out.RawByte('{')
	first := true
	_ = first
	if in.Color != "" {
		if !first {
			out.RawByte(',')
		}
		first = false
		out.RawString("\"color\":")
		out.String(string(in.Color))
	}
	if in.LabelId != 0 {
		if !first {
			out.RawByte(',')
		}
		first = false
		out.RawString("\"label_id\":")
		out.Int32(int32(in.LabelId))
	}
	if in.Name != "" {
		if !first {
			out.RawByte(',')
		}
		first = false
		out.RawString("\"name\":")
		out.String(string(in.Name))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v GetCharactersCharacterIdMailLabels200Ok) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson3813a42fEncodeGithubComAntihaxGoesiV21(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v GetCharactersCharacterIdMailLabels200Ok) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson3813a42fEncodeGithubComAntihaxGoesiV21(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *GetCharactersCharacterIdMailLabels200Ok) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson3813a42fDecodeGithubComAntihaxGoesiV21(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *GetCharactersCharacterIdMailLabels200Ok) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson3813a42fDecodeGithubComAntihaxGoesiV21(l, v)
}
